/** CronogramaCPT 1.5.0. Agenda compartilhada com versões, conflito de edição e histórico. */
class PerfisCPT {
  static get papeis(){return ['administrador','gestao','atendimento','socioambiental','comunicacao'];}
  static todos(){const p=PropertiesService.getScriptProperties().getProperties();return Object.keys(p).filter(k=>k.startsWith('CPT_PESSOA:')).map(k=>JSON.parse(p[k])).sort((a,b)=>a.nome.localeCompare(b.nome));}
  static obter(email,c){if(email===c.administrador)return {email,nome:'Victor Xavier',papeis:['administrador','gestao','atendimento','socioambiental','comunicacao'],ativo:true};const raw=PropertiesService.getScriptProperties().getProperty('CPT_PESSOA:'+email);const p=raw?JSON.parse(raw):null;if(!p||!p.ativo)throw new Error('Seu acesso ainda não está ativo. Peça ao administrador para cadastrar seu e-mail em Equipe e acessos.');return p;}
  static gerencia(p){return p.papeis.some(x=>['administrador','gestao'].includes(x));}
  static admin(p){if(!p.papeis.includes('administrador'))throw new Error('Esta ação é exclusiva do administrador.');}
  static lista(c){return [this.obter(c.administrador,c),...this.todos().filter(p=>p.email!==c.administrador)];}
  static salvar(ctx,p){this.admin(ctx.perfil);if(!p||typeof p.email!=='string'||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email)||p.email.length>180)throw new Error('Informe um e-mail válido.');const email=p.email.trim().toLowerCase();if(email===ctx.config.administrador)throw new Error('O administrador principal permanece ativo.');if(typeof p.nome!=='string'||!p.nome.trim()||p.nome.length>100||!Array.isArray(p.papeis)||!p.papeis.length||p.papeis.some(x=>!this.papeis.includes(x))||typeof p.ativo!=='boolean')throw new Error('Confira o nome, as funções e a situação do acesso.');const key='CPT_PESSOA:'+email,props=PropertiesService.getScriptProperties();const anterior=JSON.parse(props.getProperty(key)||'null'),versao=(anterior?.versao||0)+1;if(Number(p.versao||0)!==(anterior?.versao||0))throw new Error('Este cadastro mudou. Reabra a equipe antes de salvar.');const novo={email,nome:p.nome.trim(),papeis:[...new Set(p.papeis)],ativo:p.ativo,versao,alteradoEm:new Date().toISOString(),alteradoPor:ctx.email};props.setProperty('CPT_PESSOA_HIST:'+email+':'+versao,JSON.stringify({anterior,novo}));props.setProperty(key,JSON.stringify(novo));return {resultado:'Acesso salvo.',pessoa:novo};}
}
class CronogramaCPT {
  static get cabecalho(){return ['ID','Versão','Operação ID','Alterado em','Alterado por','Conteúdo JSON'];}
  constructor(ctx){this.ctx=ctx;}
  static data(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw new Error('Informe uma data válida.');return v;}
  static texto(v,max,obrigatorio=false){if(typeof v!=='string'||v.length>max||(obrigatorio&&!v.trim()))throw new Error('Confira os campos obrigatórios e o tamanho do texto.');return v.trim();}
  aba(){if(!this.ctx.config.agendaId)throw new Error('Execute atualizarAplicacaoCPT12 no editor para preparar o cronograma.');let a;try{a=SpreadsheetApp.openById(this.ctx.config.agendaId).getSheetByName('Eventos');}catch(_){throw new Error('Peça acesso à planilha da agenda compartilhada.');}if(!a||a.getRange(1,1,1,6).getValues()[0].some((v,i)=>v!==CronogramaCPT.cabecalho[i]))throw new Error('A estrutura da agenda precisa ser conferida.');return a;}
  ler(){const a=this.aba(),n=a.getLastRow()-1,rows=n>0?a.getRange(2,1,n,6).getValues():[],atuais=new Map();rows.forEach(r=>{if(!r[0])return;const e=JSON.parse(r[5]);if(!atuais.has(e.id)||atuais.get(e.id).versao<e.versao)atuais.set(e.id,e);});return {a,rows,atuais};}
  publico(e){const {assinaturaPedido,...publico}=e;return publico;}
  podeEditar(e){return (PerfisCPT.gerencia(this.ctx.perfil)||e.criadoPor===this.ctx.email||e.responsaveis.includes(this.ctx.email));}
  listar(p){p=p||{};const mes=String(p.mes||'');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(mes))throw new Error('Selecione um mês válido.');const {atuais}=this.ler();const itens=[...atuais.values()].filter(e=>e.data.startsWith(mes)).map(e=>({...this.publico(e),podeEditar:this.podeEditar(e)}));return {itens:itens.sort((a,b)=>(a.data+a.inicio+a.titulo).localeCompare(b.data+b.inicio+b.titulo)),pessoas:PerfisCPT.lista(this.ctx.config).filter(p=>p.ativo).map(p=>({email:p.email,nome:p.nome,papeis:p.papeis})),perfil:this.ctx.perfil};}
  salvar(p){if(!p||typeof p.operacaoId!=='string'||!/^OP-[a-zA-Z0-9-]{12,70}$/.test(p.operacaoId))throw new Error('Identificação de salvamento inválida. Reabra a atividade.');const assinatura=JSON.stringify(['id','versao','titulo','descricao','obra','bairro','data','inicio','fim','frentes','responsaveis','natureza','status','motivo'].map(k=>p[k]??''));const {a,rows,atuais}=this.ler();const repetido=rows.find(r=>String(r[2])===p.operacaoId);if(repetido){if(String(repetido[4])!==this.ctx.email)throw new Error('Operação inválida.');const anterior=JSON.parse(repetido[5]);if(anterior.assinaturaPedido!==assinatura)throw new Error('O primeiro salvamento já foi concluído. Feche e reabra a atividade antes de aplicar novas alterações.');return {resultado:'Atividade já salva.',evento:this.publico(anterior)};}
    const antigo=p.id?atuais.get(p.id):null;if(p.id&&!antigo)throw new Error('Atividade não encontrada.');if(antigo&&!this.podeEditar(antigo))throw new Error('Somente responsáveis, autor ou gestão podem alterar esta atividade.');if(antigo&&Number(p.versao)!==antigo.versao)throw new Error('Outra pessoa atualizou esta atividade. Feche e abra novamente para conferir a versão atual.');
    const data=CronogramaCPT.data(p.data),inicio=CronogramaCPT.texto(p.inicio||'',5),fim=CronogramaCPT.texto(p.fim||'',5);if((inicio&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(inicio))||(fim&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(fim))||!!inicio!==!!fim||(inicio&&fim<=inicio))throw new Error('Preencha início e fim válidos; o fim deve ser depois do início.');
    const areas=['atendimento','socioambiental','comunicacao','gestao','administrativo'];if(!Array.isArray(p.frentes)||!p.frentes.length||p.frentes.some(x=>!areas.includes(x)))throw new Error('Selecione ao menos uma frente.');if(!antigo&&!PerfisCPT.gerencia(this.ctx.perfil)&&!p.frentes.some(x=>this.ctx.perfil.papeis.includes(x)))throw new Error('Inclua sua frente na atividade.');
    const pessoas=PerfisCPT.lista(this.ctx.config).filter(x=>x.ativo).map(x=>x.email);if(!Array.isArray(p.responsaveis)||!p.responsaveis.length||p.responsaveis.some(x=>!pessoas.includes(x)))throw new Error('Escolha ao menos um responsável ativo.');if(!['interno','externo'].includes(p.natureza)||!['planejada','confirmada','concluida','cancelada'].includes(p.status))throw new Error('Confira a classificação e a situação.');
    const motivo=CronogramaCPT.texto(p.motivo||'',600),reagendado=!!antigo&&(antigo.data!==data||antigo.inicio!==inicio||antigo.fim!==fim),cancelando=p.status==='cancelada'&&(!antigo||antigo.status!=='cancelada');if((reagendado||cancelando)&&!motivo)throw new Error('Informe o motivo do reagendamento ou cancelamento para registrar no histórico.');
    const agora=new Date().toISOString(),e={assinaturaPedido:assinatura,id:antigo?.id||'AG-'+Utilities.getUuid(),versao:(antigo?.versao||0)+1,titulo:CronogramaCPT.texto(p.titulo,140,true),descricao:CronogramaCPT.texto(p.descricao||'',2500),obra:CronogramaCPT.texto(p.obra||'',200),bairro:CronogramaCPT.texto(p.bairro||'',150),data,inicio,fim,frentes:[...new Set(p.frentes)],responsaveis:[...new Set(p.responsaveis)],natureza:p.natureza,status:p.status,criadoPor:antigo?.criadoPor||this.ctx.email,criadoEm:antigo?.criadoEm||agora,alteradoPor:this.ctx.email,alteradoEm:agora};
    e.motivo=motivo;e.acao=!antigo?'Criação':cancelando?'Cancelamento':reagendado?'Reagendamento':antigo.status==='cancelada'&&e.status!=='cancelada'?'Reativação':'Edição';e.camposAlterados=['titulo','descricao','obra','bairro','data','inicio','fim','frentes','responsaveis','natureza','status'].filter(k=>!antigo||JSON.stringify(antigo[k])!==JSON.stringify(e[k]));
    // Uma linha contém simultaneamente o estado completo e a revisão. Não apaga versões anteriores.
    a.getRange(a.getLastRow()+1,1,1,6).setValues([[e.id,e.versao,p.operacaoId,agora,this.ctx.email,JSON.stringify(e)]]);return {resultado:'Atividade salva no cronograma compartilhado.',evento:{...this.publico(e),podeEditar:true}};
  }
  historico(id){const {rows}=this.ler();return {versoes:rows.filter(r=>String(r[0])===id).map(r=>this.publico(JSON.parse(r[5]))).reverse()};}
}
function contextoCronogramaCPT_(){return AplicacaoCPT.contexto();}
function carregarCronogramaCPT(p){return DesempenhoCPT.medir('agenda.consultar',()=>new CronogramaCPT(contextoCronogramaCPT_()).listar(p));}
function salvarAtividadeCPT(p){const lock=LockService.getScriptLock();if(!lock.tryLock(15000))throw new Error('Há outro salvamento em andamento. Tente novamente.');try{return DesempenhoCPT.medir('agenda.salvar',()=>new CronogramaCPT(contextoCronogramaCPT_()).salvar(p));}finally{lock.releaseLock();}}
function historicoAtividadeCPT(id){return DesempenhoCPT.medir('agenda.historico',()=>new CronogramaCPT(contextoCronogramaCPT_()).historico(String(id)));}
function listarEquipeCPT(){const c=contextoCronogramaCPT_();PerfisCPT.admin(c.perfil);return {pessoas:PerfisCPT.lista(c.config),agendaUrl:'https://docs.google.com/spreadsheets/d/'+c.config.agendaId+'/edit'};}
function salvarPessoaCPT(p){const l=LockService.getScriptLock();if(!l.tryLock(15000))throw new Error('Tente salvar novamente.');try{const c=contextoCronogramaCPT_();return PerfisCPT.salvar(c,p);}finally{l.releaseLock();}}
/** Execute uma vez, no mesmo projeto CPT — Aplicação. Reexecutar não duplica a agenda. */
function atualizarAplicacaoCPT12(){const l=LockService.getScriptLock();if(!l.tryLock(15000))throw new Error('Tente novamente.');try{const email=AplicacaoCPT.conta(),c=AplicacaoCPT.config();if(email!==c.administrador)throw new Error('Somente o administrador principal instala a agenda.');if(!c.agendaId){const ss=SpreadsheetApp.create('CPT • Agenda compartilhada');c.agendaId=ss.getId();PropertiesService.getScriptProperties().setProperty(AplicacaoCPT.chave,JSON.stringify(c));}const ss=SpreadsheetApp.openById(c.agendaId);ss.setSpreadsheetTimeZone('America/Sao_Paulo');let a=ss.getSheetByName('Eventos');if(!a){a=ss.getSheets()[0];if(a.getLastRow()>0)throw new Error('A agenda recém-criada contém dados inesperados.');a.setName('Eventos');}if(a.getLastRow()===0)a.getRange(1,1,1,6).setValues([CronogramaCPT.cabecalho]);if(a.getRange(1,1,1,6).getValues()[0].some((v,i)=>v!==CronogramaCPT.cabecalho[i]))throw new Error('Cabeçalho da agenda incompatível. Instalação interrompida sem substituir os dados.');a.setFrozenRows(1);a.getRange(1,1,1,6).setFontWeight('bold').setBackground('#123f71').setFontColor('#ffffff');c.versao='1.5.0';PropertiesService.getScriptProperties().setProperty(AplicacaoCPT.chave,JSON.stringify(c));const r={resultado:'CPT 1.2 CONFIGURADA',agenda:'https://docs.google.com/spreadsheets/d/'+c.agendaId+'/edit',gatilhosCriados:0,baseCampoAlterada:false,proximoPasso:'Publique uma nova versão da implantação. Cadastre a equipe dentro da aplicação e compartilhe a agenda com os colaboradores que vão editar.'};console.log(JSON.stringify(r,null,2));return r;}finally{l.releaseLock();}}
