const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto');let email='victor@example.com',locked=false,created=0;const props=new Map([['CPT_APLICACAO_1',JSON.stringify({baseId:'base',administrador:email,versao:'1.0.0'})]]);const books=new Map();
class Sheet{constructor(name){this.name=name;this.rows=[];}getLastRow(){return this.rows.length}getName(){return this.name}setName(n){this.name=n;return this}setFrozenRows(){return this}getRange(r,c,n=1,m=1){const self=this;return {getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>self.rows[r+i-1]?.[c+j-1]??'')),setValues:rs=>{rs.forEach((row,i)=>{self.rows[r+i-1]??=[];row.forEach((v,j)=>self.rows[r+i-1][c+j-1]=v)});return this.getRange(r,c,n,m)},setFontWeight:()=>this.getRange(r,c,n,m),setBackground:()=>this.getRange(r,c,n,m),setFontColor:()=>this.getRange(r,c,n,m)}}}
class Book{constructor(id){this.id=id;this.sheets=[new Sheet('Planilha1')]}insertSheet(n){const a=new Sheet(n);this.sheets.push(a);return a;}getId(){return this.id}getName(){return this.id}getSheets(){return this.sheets}getSheetByName(n){return this.sheets.find(s=>s.name===n)||null}setSpreadsheetTimeZone(){return this}getSpreadsheetTimeZone(){return 'America/Sao_Paulo'}}books.set('base',new Book('base'));
const ctx={Date,console,Session:{getActiveUser:()=>({getEmail:()=>email}),getEffectiveUser:()=>({getEmail:()=>email})},PropertiesService:{getScriptProperties:()=>({getProperties:()=>Object.fromEntries(props),getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,v)})},SpreadsheetApp:{openById:id=>{if(!books.has(id))throw Error('Não existe');return books.get(id)},create:()=>{created++;const b=new Book('agenda'+created);books.set(b.id,b);return b}},Utilities:{getUuid:()=>crypto.randomUUID(),formatDate:()=> '2026-09-30'},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;return true},releaseLock:()=>locked=false})}};vm.createContext(ctx);for(const f of ['DesempenhoCPT','DadosDaAplicacao','PerfisCPT','CronogramaCPT','ObservacoesCPT','AplicacaoCPT'])vm.runInContext(fs.readFileSync(__dirname+'/../src/'+f+'.gs','utf8'),ctx);const run=s=>vm.runInContext(s,ctx),plain=x=>JSON.parse(JSON.stringify(x));
run('prepararDadosDaAplicacaoCPT()');run('prepararDadosDaAplicacaoCPT()');assert.equal(created,1);assert.equal(books.get('base').sheets[0].rows.length,0);
ctx.person={email:'paula@example.com',nome:'Paula',papeis:['comunicacao'],ativo:true,versao:0};run('salvarPessoaCPT(person)');assert.equal(run('listarEquipeCPT().pessoas.length'),2);assert.throws(()=>run('salvarPessoaCPT(person)'),/mudou/);
ctx.payload={operacaoId:'OP-123456789012345',id:'',versao:0,titulo:'Atividade de campo',data:'2026-09-30',inicio:'09:00',fim:'10:00',descricao:'Texto',obra:'Obra',bairro:'Bairro',frentes:['socioambiental'],responsaveis:['victor@example.com'],natureza:'externo',status:'planejada'};
const e=plain(run('salvarAtividadeCPT(payload).evento'));const e2=plain(run('salvarAtividadeCPT(payload).evento'));assert.equal(e.id,e2.id);assert.equal(run("carregarCronogramaCPT({mes:'2026-09'}).itens.length"),1);ctx.payload.titulo='Outro texto';assert.throws(()=>run('salvarAtividadeCPT(payload)'),/primeiro salvamento/);ctx.payload={...ctx.payload,id:e.id,versao:1,operacaoId:'OP-123456789012346'};run('salvarAtividadeCPT(payload)');ctx.payload.operacaoId='OP-123456789012347';assert.throws(()=>run('salvarAtividadeCPT(payload)'),/Outra pessoa/);ctx.ident=e.id;assert.equal(run('historicoAtividadeCPT(ident).versoes.length'),2);
ctx.payload={...ctx.payload,versao:2,data:'2026-02-31'};assert.throws(()=>run('salvarAtividadeCPT(payload)'),/data válida/);ctx.payload.data='2026-09-30';ctx.payload.fim='08:00';assert.throws(()=>run('salvarAtividadeCPT(payload)'),/fim/);ctx.payload.fim='10:00';
email='paula@example.com';assert.throws(()=>run('salvarAtividadeCPT(payload)'),/responsáveis/);assert.throws(()=>run('listarEquipeCPT()'),/administração técnica/);ctx.payload={...ctx.payload,id:'',versao:0,operacaoId:'OP-paula123456789',frentes:['comunicacao'],responsaveis:['paula@example.com']};run('salvarAtividadeCPT(payload)');assert.equal(run("carregarCronogramaCPT({mes:'2026-09'}).itens.length"),2);
email='desconhecido@example.com';assert.throws(()=>run("carregarCronogramaCPT({mes:'2026-09'})"),/acesso/);email='victor@example.com';props.set('CPT_ROTACOES',JSON.stringify([{inicio:'2026-09-30',nomes:['Victor','Paula','Cintia']}]));assert.equal(run("carregarCronogramaCPT({mes:'2026-10'}).itens.length"),0);assert.equal(run('typeof salvarRotacaoCPT'),'undefined');assert.equal(locked,false);assert.equal(books.get('agenda1').getSheetByName('Eventos').rows.length,4);
console.log('PASS: instalação repetida, perfis, bloqueio de acesso, conflitos, repetição segura, validações, histórico, ausência de rotação automática e nenhuma escrita na base Campo.');

assert(!('assinaturaPedido' in e));assert(!('assinaturaPedido' in plain(run("carregarCronogramaCPT({mes:'2026-09'}).itens[0]"))));
const b=books.get('base');for(const n of ['Registros','Atendimentos']){const a=new Sheet(n);a.rows=[['Cabeçalho']];b.sheets.push(a);}const saude=plain(run('conferirSaudeCPT()'));assert.equal(saude.itens.length,4);assert.equal(saude.itens[2].quantidade,3);email='paula@example.com';assert.throws(()=>run('conferirSaudeCPT()'),/administração técnica/);email='victor@example.com';
const tab=books.get('agenda1').getSheetByName('Eventos'),cab=tab.rows[0][0];tab.rows[0][0]='Incompatível';assert.throws(()=>run('prepararDadosDaAplicacaoCPT()'),/incompatível/);assert.equal(tab.rows[0][0],'Incompatível');tab.rows[0][0]=cab;
console.log('PASS: contratos menores, saúde restrita ao administrador e cabeçalho incompatível preservado.');
ctx.payload={...ctx.payload,id:e.id,versao:2,operacaoId:'OP-reagenda12345678',data:'2026-10-01',responsaveis:['victor@example.com'],motivo:''};
assert.throws(()=>run('salvarAtividadeCPT(payload)'),/motivo/);ctx.payload.motivo='Mudança solicitada pela equipe';const moved=plain(run('salvarAtividadeCPT(payload).evento'));assert.equal(moved.acao,'Reagendamento');assert(moved.camposAlterados.includes('data'));assert.equal(run("carregarCronogramaCPT({mes:'2026-10'}).itens.length"),1);
ctx.payload={...ctx.payload,versao:3,operacaoId:'OP-cancela123456789',status:'cancelada',motivo:''};assert.throws(()=>run('salvarAtividadeCPT(payload)'),/motivo/);ctx.payload.motivo='Atividade suspensa';const canceled=plain(run('salvarAtividadeCPT(payload).evento'));assert.equal(canceled.acao,'Cancelamento');assert.equal(run('historicoAtividadeCPT(ident).versoes.length'),4);assert.equal(plain(run('salvarAtividadeCPT(payload).evento')).versao,4);
ctx.payload={...ctx.payload,versao:4,operacaoId:'OP-reativa123456789',status:'planejada',motivo:'Retomada autorizada'};assert.equal(plain(run('salvarAtividadeCPT(payload).evento')).acao,'Reativação');console.log('PASS: motivo obrigatório, reagendamento entre meses, cancelamento idempotente, reativação e revisões preservadas.');
const at=books.get('base').getSheetByName('Atendimentos');at.rows=[plain(run('DadosDaAplicacao.colunasAtd')),['A','A','','Aberto'],['B','A','Incorporado','Aberto']];const mov=new Sheet('Movimentações');mov.rows=[['ID','Protocolo','Data e hora','Tipo','Status','Autor','Resumo','Origem'],...Array.from({length:35},(_,i)=>['M'+i,i%2?'A':'B','01/10/2026','Atualização','Aberto','Equipe','Resumo '+i,'Importado']),['X','OUTRO','','','','','Não deve aparecer','']];books.get('base').sheets.push(mov);let h=plain(run("consultarHistoricoFichaCPT({protocolo:'B'})"));assert.equal(h.itens.length,30);assert(h.itens.every(x=>x.protocolo==='A'||x.protocolo==='B'));ctx.next=h.proximoCursor;assert.equal(run("consultarHistoricoFichaCPT({protocolo:'A',cursor:next}).itens.length"),5);email='paula@example.com';assert.equal(run("consultarHistoricoFichaCPT({protocolo:'A'}).itens.length"),30);assert.equal(run("buscarAtendimentosCPT({}).total"),1);assert(run('conferirMeuAcessoCPT().etapas.every(x=>x.ok)'));email='semcadastro@example.com';assert.equal(run('conferirMeuAcessoCPT().etapas[1].ok'),false);email='victor@example.com';console.log('PASS: histórico paginado, protocolos incorporados, consulta comum a toda a equipe e diagnóstico por conta.');
// Observações: evento novo no caso principal, idempotente, nunca altera a ficha.
email='paula@example.com';ctx.obs={protocolo:'B',canal:'Campo / itinerante',texto:'Moradora informou retorno do vazamento.',operacaoId:'OP-observacao123456'};
const o1=plain(run('adicionarObservacaoCPT(obs)'));assert.equal(o1.observacao.protocolo,'A');assert.equal(o1.observacao.consultado,'B');assert.equal(plain(run('adicionarObservacaoCPT(obs)')).observacao.id,o1.observacao.id);
ctx.obs={...ctx.obs,texto:'Outro texto'};assert.throws(()=>run('adicionarObservacaoCPT(obs)'),/já foi registrada/);ctx.obs={...ctx.obs,operacaoId:'OP-observacao999999',canal:'Pombo'};assert.throws(()=>run('adicionarObservacaoCPT(obs)'),/por onde/);
ctx.obs={...ctx.obs,canal:'Escritório',texto:'   '};assert.throws(()=>run('adicionarObservacaoCPT(obs)'),/obrigatórios/);ctx.obs={...ctx.obs,protocolo:'NAOEXISTE',texto:'x'};assert.throws(()=>run('adicionarObservacaoCPT(obs)'),/não encontrado/);
const lista=plain(run("listarObservacoesCPT({protocolo:'A'})"));assert.equal(lista.itens.length,1);assert.equal(lista.itens[0].nome,'Paula');assert.deepEqual(at.rows[2],['B','A','Incorporado','Aberto']);assert.equal(locked,false);
// Perfil carregado sem abrir planilhas; conta fora do domínio bloqueada; administrativo tem visão de gestão.
const cfg=JSON.parse(props.get('CPT_APLICACAO_1'));props.set('CPT_APLICACAO_1',JSON.stringify({...cfg,dominio:'example.com'}));const abrir=ctx.SpreadsheetApp.openById;ctx.SpreadsheetApp.openById=()=>{throw Error('não deveria abrir planilha')};
assert.deepEqual(plain(run('carregarPerfilCPT()')).perfil.papeis,['comunicacao']);ctx.SpreadsheetApp.openById=abrir;email='alguem@gmail.com';assert.throws(()=>run('carregarPerfilCPT()'),/exclusiva/);email='';assert.throws(()=>run('carregarPerfilCPT()'),/identificar sua conta/);
email='victor@example.com';assert.equal(plain(run('carregarPerfilCPT()')).perfil.papeis.length,7);ctx.person={email:'adm@gmail.com',nome:'X',papeis:['administrativo'],ativo:true,versao:0};assert.throws(()=>run('salvarPessoaCPT(person)'),/conta @example.com/);
ctx.person={email:'adm@example.com',nome:'Adm',papeis:['administrativo'],ativo:true,versao:0};run('salvarPessoaCPT(person)');assert.equal(books.get('agenda1').getSheetByName('Histórico de acessos').rows.length,3);assert(run("PerfisCPT.gerencia(PerfisCPT.obter('adm@example.com',JSON.parse(PropertiesService.getScriptProperties().getProperty('CPT_APLICACAO_1'))))"));
email='adm@example.com';assert.throws(()=>run('listarEquipeCPT()'),/administração técnica/);email='victor@example.com';ctx.person={email:'victor@example.com',nome:'Victor',papeis:['gestao'],ativo:true,versao:0};assert.throws(()=>run('salvarPessoaCPT(person)'),/proprietário/);
console.log('PASS: observações por caso, bootstrap de perfil sem planilhas, domínio exigido, Administrativo sem administração técnica.');
