const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto');let email='victor@example.com',locked=false,created=0;const props=new Map([['CPT_APLICACAO_1',JSON.stringify({baseId:'base',administrador:email,versao:'1.0.0'})]]);const books=new Map();
class Sheet{constructor(name){this.name=name;this.rows=[];}getLastRow(){return this.rows.length}getName(){return this.name}setName(n){this.name=n;return this}setFrozenRows(){return this}getRange(r,c,n=1,m=1){const self=this;return {getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>self.rows[r+i-1]?.[c+j-1]??'')),setValues:rs=>{rs.forEach((row,i)=>{self.rows[r+i-1]??=[];row.forEach((v,j)=>self.rows[r+i-1][c+j-1]=v)});return this.getRange(r,c,n,m)},setFontWeight:()=>this.getRange(r,c,n,m),setBackground:()=>this.getRange(r,c,n,m),setFontColor:()=>this.getRange(r,c,n,m)}}}
class Book{constructor(id){this.id=id;this.sheets=[new Sheet('Planilha1')]}insertSheet(n){const a=new Sheet(n);this.sheets.push(a);return a;}getId(){return this.id}getName(){return this.id}getSheets(){return this.sheets}getSheetByName(n){return this.sheets.find(s=>s.name===n)||null}setSpreadsheetTimeZone(){return this}getSpreadsheetTimeZone(){return 'America/Sao_Paulo'}}books.set('base',new Book('base'));
const ctx={Date,console,Session:{getActiveUser:()=>({getEmail:()=>email}),getEffectiveUser:()=>({getEmail:()=>email})},PropertiesService:{getScriptProperties:()=>({getProperties:()=>Object.fromEntries(props),getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,v)})},SpreadsheetApp:{openById:id=>{if(!books.has(id))throw Error('Não existe');return books.get(id)},create:()=>{created++;const b=new Book('agenda'+created);books.set(b.id,b);return b}},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,v)=>[...crypto.createHash('sha256').update(v).digest()],getUuid:()=>crypto.randomUUID(),formatDate:()=> '2026-09-30'},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;return true},releaseLock:()=>locked=false})}};vm.createContext(ctx);for(const f of ['CacheCPT','DesempenhoCPT','DadosDaAplicacao','SocioambientalCPT','PerfisCPT','CronogramaCPT','ObservacoesCPT','RelatorioMensalCPT','AplicacaoCPT','EntregasCPT'])vm.runInContext(fs.readFileSync(__dirname+'/../src/'+f+'.gs','utf8'),ctx);const run=s=>vm.runInContext(s,ctx),plain=x=>JSON.parse(JSON.stringify(x));

run('prepararDadosDaAplicacaoCPT()');
ctx.source={registro:{id:'REG-'+'a'.repeat(24),procedimento:'Relato de atividade',atividade:'Atividade exemplo'},campos:[{titulo:'Relato',valor:'Conteúdo original'}],anexos:[{id:'imagem1234567890'}]};run('DadosDaAplicacao.prototype.detalhe=function(id){if(id!==source.registro.id)throw Error("ID inválido");return source;}');
ctx.id=ctx.source.registro.id;let loaded=plain(run('carregarEntregaRelatoCPT(id)'));assert.equal(loaded.entrega,null);assert.equal(books.get('agenda1').getSheetByName('Entregas'),null);
ctx.p={id:ctx.id,versao:0,fonteHash:loaded.hash,titulo:'Relato pronto',texto:'Texto revisado',situacao:'rascunho',fotos:[{id:'imagem1234567890',legenda:'Atividade'}],operacaoId:'OP-primeira12345678'};let saved=plain(run('salvarEntregaRelatoCPT(p)'));assert.equal(saved.entrega.versao,1);assert(!('assinatura' in saved.entrega));assert.equal(run('salvarEntregaRelatoCPT(p).entrega.versao'),1);assert.equal(books.get('agenda1').getSheetByName('Entregas').rows.length,2);
ctx.p.operacaoId='OP-conflito12345678';assert.throws(()=>run('salvarEntregaRelatoCPT(p)'),/Outra pessoa/);ctx.p.versao=1;ctx.p.fotos=[{id:'imagemFORA12345',legenda:''}];assert.throws(()=>run('salvarEntregaRelatoCPT(p)'),/não pertence/);ctx.p.fotos=[];ctx.source.campos[0].valor='Texto alterado';assert.throws(()=>run('salvarEntregaRelatoCPT(p)'),/original mudou/);assert.equal(run('carregarEntregaRelatoCPT(id).fonteAlterada'),true);ctx.p.fonteHash=run('carregarEntregaRelatoCPT(id).hash');ctx.p.situacao='pronto';assert.equal(run('salvarEntregaRelatoCPT(p).entrega.versao'),2);assert.equal(run('carregarEntregaRelatoCPT(id).historico.length'),2);
props.set('CPT_PESSOA:atd@example.com',JSON.stringify({email:'atd@example.com',nome:'ATD',ativo:true,papeis:['atendimento']}));email='atd@example.com';assert.throws(()=>run('carregarEntregaRelatoCPT(id)'),/disponível/);email='victor@example.com';ctx.source.registro.procedimento='Ficha de Atendimento';assert.throws(()=>run('carregarEntregaRelatoCPT(id)'),/relatos de atividade/);assert.equal(locked,false);console.log('PASS: criação sob demanda, idempotência, conflitos, fonte alterada, anexo alheio recusado, perfil e original preservado.');
