from pathlib import Path
root=Path(__file__).resolve().parents[1]
mock=r'''<script>
const perfilDemo={email:'victor@example.com',nome:'Victor Xavier',ativo:true,emTeste:true,papeis:['administrador','administrativo','gestao','atendimento','socioambiental','comunicacao','comercializacao']};
let obsDemo=[];let obrasDemo=[{id:'OBR-0117',nome:'Viela Sanitária x Carijós – Obra Córrego',bairros:['Jardim do Estádio','Vila Linda'],noFormulario:true,noFormularioAgora:true,situacao:'Em andamento',inicioObra:'2026-08-19',inicioComunicacao:'2026-08-19',termino:'',publico:'C',impacto:'Alto',observacao:'Ampliação da rede de esgoto.',atualizadoEm:new Date(Date.now()-864e5).toISOString(),logradouroPAC16:'Viela Sanitária',metodoPAC16:'Vala',tipo:'Rede coletora',endereco:'',latitude:null,longitude:null,nomeUso:'Viela Carijós',apelidos:['Obra do córrego grande'],exibir:'Viela Carijós'},{id:'OBR-0074',nome:'Córrego Apiaí – Margem Esquerda Orquídea',bairros:['Vila Linda'],noFormulario:true,noFormularioAgora:true,situacao:'Paralisada',inicioObra:'2026-07-16',inicioComunicacao:'2026-07-16',termino:'',publico:'A, B',impacto:'Médio',observacao:'',atualizadoEm:new Date(Date.now()-12*864e5).toISOString(),logradouroPAC16:'',metodoPAC16:'',tipo:'',endereco:'Rua das Orquídeas',latitude:null,longitude:null,nomeUso:'',apelidos:[],exibir:'Córrego Apiaí – Margem Esquerda Orquídea'}];let bairrosDemo=[{id:'BAI-001',nome:'Jardim do Estádio',noFormulario:true,apelidos:[]},{id:'BAI-002',nome:'Vila Assunção',noFormulario:true,apelidos:[]},{id:'BAI-003',nome:'Vila Linda',noFormulario:true,apelidos:['V. Linda']}];
const equipeDemo=[perfilDemo,{email:'paula@example.com',nome:'Comunicadora de exemplo',ativo:true,papeis:['comunicacao']},{email:'social@example.com',nome:'Equipe social de exemplo',ativo:true,papeis:['socioambiental']}];
let entregaDemo=null;
let eventosDemo=[{id:'AG-demo1',versao:1,titulo:'Sensibilização com moradores',data:'2026-09-30',inicio:'09:00',fim:'10:30',frentes:['socioambiental','comunicacao'],responsaveis:['social@example.com','paula@example.com'],natureza:'externo',status:'confirmada',descricao:'Atividade fictícia para explorar a interface.',obra:'Frente demonstrativa',bairro:'Vila Linda',alteradoPor:'victor@example.com',podeEditar:true},{id:'AG-demo2',versao:1,titulo:'Conferência das entregas do mês',data:'2026-09-30',inicio:'14:00',fim:'15:00',frentes:['administrativo'],responsaveis:['victor@example.com'],natureza:'interno',status:'planejada',descricao:'Exemplo de planejamento interno.',obra:'',bairro:'',alteradoPor:'victor@example.com',podeEditar:true}];
// Atividades de exemplo para hoje e os próximos dias (a página inicial mostra "Hoje na agenda").
(()=>{const d0=new Date(Date.now()-3*3600e3),iso=n=>{const d=new Date(d0);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);},ev=(id,titulo,n,inicio,fim,frentes,bairro,obra)=>({id,versao:1,titulo,data:iso(n),inicio,fim,frentes,responsaveis:['social@example.com'],natureza:'externo',status:'confirmada',descricao:'Atividade fictícia da prévia.',obra:obra||'',bairro,alteradoPor:'victor@example.com',podeEditar:true});
eventosDemo.push(ev('AG-hoje1','Plantão de atendimento na tenda',0,'09:00','12:00',['atendimento','socioambiental'],'Vila Linda','Coletor tronco A'),ev('AG-hoje2','Oficina de horta na escola',0,'14:00','16:00',['socioambiental','comunicacao'],'Jardim do Estádio'),
  ev('AG-prox1','Reunião com lideranças do bairro',1,'10:00','11:30',['gestao','socioambiental','administrativo'],'Vila Assunção'),ev('AG-prox2','Panfletagem do aviso de obra',3,'08:30','11:00',['comunicacao','comercializacao','atendimento'],'Vila Linda','Coletor tronco A'));})();

window.CPT_PREVIA={chamadas:[],chamar:async function(nome,p){const lat=Number(new URLSearchParams(location.search).get('latencia')||180),t0=performance.now();await new Promise(r=>setTimeout(r,lat));window.CPT_PREVIA.chamadas.push({nome,inicio:Math.round(t0),fim:Math.round(performance.now()+0)});
const registros=Array.from({length:36},(_,i)=>({id:'REG-'+String(i).padStart(24,'0'),procedimento:i%3?'Relato de atividade':'Pesquisa de Satisfação',data:'2026-09-'+String(28-i%22).padStart(2,'0'),atividade:['Diálogo com moradores','Sensibilização em frente de obra','Água, cuidado e território'][i%3],bairro:['Vila Linda','Jardim do Estádio','Vila Assunção'][i%3],responsavel:'Equipe de exemplo',obra:'Frente de obra demonstrativa',origem:'Dados fictícios',conferencia:''}));
const casos=Array.from({length:7},(_,i)=>({caso:'Caso '+(12+i),protocolo:'ATD2026'+String(12+i).padStart(4,'0'),nome:'Pessoa de exemplo '+(i+1),assunto:['Orientação sobre a obra','Solicitação de vistoria','Recomposição da calçada'][i%3],endereco:'Endereço fictício · Santo André',area:'Atendimento',status:i<2?'Concluído':'Em acompanhamento',concluido:i<2,abertura:'2026-09-12',conclusao:i<2?'2026-09-28':'',responsavel:'Equipe de exemplo',obra:'Frente demonstrativa',origem:'Demonstração',proximaAcao:'Conferir o retorno da equipe responsável.',atualizacao:'Informação fictícia para demonstrar a interface.',dias:[20,16,5,35,64,8,2][i]}));
if(nome==='carregarPerfilCPT'){const forced=new URLSearchParams(location.search).get('perfil');if(forced==='negado')throw new Error('Sua conta (alguem@veolia.com) ainda não está cadastrada ou está inativa. Peça à administração técnica para liberar seu acesso em Equipe e acessos.');/* ?liberada=1: como na produção depois de liberar para a equipe (todos no visual novo) */const lib=new URLSearchParams(location.search).get('liberada')==='1';return {conta:perfilDemo.email,perfil:forced?{...perfilDemo,nome:'Paula',papeis:[forced],emTeste:!lib}:{...perfilDemo,emTeste:!lib},versao:'2.0.0'};}
if(nome==='listarObservacoesCPT')return {protocolo:p.protocolo,itens:obsDemo.filter(x=>x.protocolo===p.protocolo).slice().reverse()};
if(nome==='adicionarObservacaoCPT'){if(!p.texto)throw new Error('Confira o campo observação (obrigatório).');const o={id:'OBS-'+crypto.randomUUID(),protocolo:p.protocolo,consultado:p.protocolo,em:new Date().toISOString(),autor:perfilDemo.email,nome:perfilDemo.nome,canal:p.canal||'Não informado',texto:p.texto};obsDemo.push(o);const agora=new Date().toISOString(),cs=(casos.find(c=>c.protocolo===p.protocolo)||{}).caso||p.protocolo;if(window.CPT_COM)window.CPT_COM.recados.unshift({id:'REC-'+crypto.randomUUID().slice(0,8),versao:1,para:{frentes:['atendimento','comunicacao','gestao','administrativo'],pessoas:[]},assunto:'Nova observação no '+cs,texto:p.texto+'\n\n— '+perfilDemo.nome,importante:false,prazo:'',vinculo:{tipo:'protocolo',id:p.protocolo,titulo:cs},situacao:'aberto',respostas:[],lidos:{[perfilDemo.email]:1},nomeAutor:perfilDemo.nome,criadoPor:perfilDemo.email,criadoEm:agora,atualizadoEm:agora});return {resultado:'Observação registrada no '+cs+'. Atendimento, Comunicação, Gestão e Administrativo receberam um recado.',observacao:o,avisou:true};}
if(nome==='conferirMeuAcessoCPT')return {etapas:[{nome:'Conta Google',ok:true,mensagem:'alguem@veolia.com'},{nome:'Cadastro na aplicação',ok:false,mensagem:'Conta não cadastrada.'}]};
if(nome==='salvarBairroCPT'){const b={id:p.id||'BAI-'+String(100+bairrosDemo.length),nome:p.nome,noFormulario:p.noFormulario,apelidos:p.apelidos||[]};bairrosDemo=bairrosDemo.filter(x=>x.id!==b.id).concat([b]).sort((x,y)=>x.nome.localeCompare(y.nome,'pt-BR'));return {resultado:'Bairro salvo apenas nesta prévia.',bairro:b};}
window.CPT_MAPA=window.CPT_MAPA||{pts:{'BAI-002':[-23.6575,-46.5290],'BAI-003':[-23.6700,-46.5450]},obraPts:{'OBR-0117':[-23.6620,-46.5330]}};
const MAPAobras=()=>obrasDemo.map(o=>{const pt=window.CPT_MAPA.obraPts[o.id];return {id:o.id,nome:o.exibir||o.nome,situacao:o.situacao,lat:pt?pt[0]:null,lng:pt?pt[1]:null,hoje:o.id==='OBR-0117',acoes:o.id==='OBR-0117'?6:0,pessoas:o.id==='OBR-0117'?80:0,casos:o.id==='OBR-0117'?2:1};});
const MAPAbairros=()=>bairrosDemo.map((b,i)=>{const pt=window.CPT_MAPA.pts[b.id];return {id:b.id,nome:b.nome,lat:pt?pt[0]:null,lng:pt?pt[1]:null,acoes:[4,9,6][i]||0,pessoas:[40,120,70][i]||0,casos:[0,3,2][i]||0};});
if(nome==='carregarMapaCPT'){const dono=!new URLSearchParams(location.search).get('perfil');if(!dono)throw new Error('O mapa está reservado à administração técnica durante o período de testes.');const hoje=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());
  const per=p.periodo==='hoje'?{tipo:'hoje',de:hoje,ate:hoje}:p.periodo==='semana'?{tipo:'semana',de:hoje,ate:hoje}:{tipo:'mes',de:p.mes+'-01',ate:p.mes+'-30'};const k=p.periodo==='hoje'?0.3:p.periodo==='semana'?0.6:1;
  const bs=MAPAbairros().map(b=>({...b,acoes:Math.round(b.acoes*k),pessoas:Math.round(b.pessoas*k),casos:Math.round(b.casos*k)})),os=MAPAobras();
  return {periodo:per,obras:os,bairros:bs,semLocal:{acoes:1,casos:1},semPonto:{obras:os.filter(o=>o.lat==null).length,bairros:bs.filter(b=>b.lat==null).length},totais:{acoes:bs.reduce((s,b)=>s+b.acoes,0)+1,pessoas:bs.reduce((s,b)=>s+b.pessoas,0),casos:bs.reduce((s,b)=>s+b.casos,0)+3},podePosicionar:dono,centro:[-23.6639,-46.5383],limites:{latMin:-23.86,latMax:-23.55,lngMin:-46.60,lngMax:-46.24}};}
if(nome==='posicionarNoMapaCPT'){if(p.lat<-23.86||p.lat>-23.55||p.lng<-46.60||p.lng>-46.24)throw new Error('O ponto ficou fora de Santo André. Aproxime o mapa e clique de novo.');(p.tipo==='obra'?window.CPT_MAPA.obraPts:window.CPT_MAPA.pts)[p.id]=[p.lat,p.lng];return {resultado:'Ponto salvo (prévia).',lat:p.lat,lng:p.lng};}
if(nome==='sugerirBairrosNoMapaCPT'){window.CPT_MAPA.pts['BAI-001']=[-23.6480,-46.5520];return {resultado:'1 bairro posicionado pela pesquisa do Google (prévia).',gravados:1,fora:[]};}
window.CPT_ENT=window.CPT_ENT||{itens:{},zip:false};
const ENTq=new URLSearchParams(location.search).get('perfil'),ENTdono=!ENTq,ENTnomes={afazer:'A fazer',preparo:'Em preparo',revisao:'Em revisão',entregue:'Entregue'};
const ENTtipos=[['relatorio','Relatório mensal','Base do relatório (itens 1 a 13), gerada aqui embaixo.',''],['anexos','Anexos do relatório','Planilha oficial: a aplicação acrescenta os casos do mês no Controle de manifestações; Matriz de Contatos e Indicadores 2026 são à mão.',''],['parceiros','Programa Parceiros','Respostas publicadas na máscara oficial.','parceiros'],['atendimentos','Atendimentos','Fichas oficiais do mês (abertas e concluídas no período) e o .zip.','']];
const ENTarq=t=>t==='anexos'?(window.CPT_ENT.anexos?{titulo:'Planilha oficial dos Anexos · atualizada',url:'https://docs.google.com/spreadsheets/d/EXEMPLO/edit',em:window.CPT_ENT.anexos.em}:null):t==='relatorio'?{titulo:'Base do relatório · versão 1',url:'https://docs.google.com/document/d/demo/edit',em:'2026-10-02T12:00:00Z'}:t==='atendimentos'?{titulo:'Pasta das fichas',url:'https://drive.google.com/drive/folders/demo',zip:window.CPT_ENT.zip?{url:'https://drive.google.com/file/d/zip/view'}:null}:null;
const ENTcartao=(mes,[id,titulo,texto,rota])=>{const x=window.CPT_ENT.itens[mes+id],a=ENTarq(id);return {tipo:id,titulo,texto,rota,situacao:x?x.situacao:a?'preparo':'afazer',responsavel:x?x.responsavel:'',prazo:x&&x.prazo?x.prazo:(()=>{const [y,m]=mes.split('-').map(Number);return new Date(Date.UTC(y,m,5)).toISOString().slice(0,10);})(),entregas:x?x.entregas:0,versao:x?x.versao:0,retratos:x?x.retratos.slice().reverse():[],arquivo:a};};
const ANXlinks={planilha:'https://docs.google.com/spreadsheets/d/EXEMPLO/edit',xlsx:'https://docs.google.com/spreadsheets/d/EXEMPLO/export?format=xlsx',pdf:'https://docs.google.com/spreadsheets/d/EXEMPLO/export?format=pdf'};
window.CPT_OBRAS_DIA=window.CPT_OBRAS_DIA||{conf:{},vinc:[{id:'REG-'+'e'.repeat(24),procedimento:'Relato de atividade',data:new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date()),bairro:'Vila Linda',responsavel:'Ana (demo)',atividade:'Plantão social na rua nova',observacao:'Obra nova na Rua das Flores, perto da escola.'}]};
const ODD=window.CPT_OBRAS_DIA,hojeO=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date()),gerO=()=>{const q=new URLSearchParams(location.search).get('perfil');return !q||['gestao','administrativo'].includes(q);};
const ativasO=()=>obrasDemo.filter(o=>['Em andamento','Paralisada','A confirmar'].includes(o.situacao)).map(o=>({id:o.id,exibir:o.exibir||o.nome,bairros:o.bairros,situacao:o.situacao}));
const missoesExtra=()=>{if(new URLSearchParams(location.search).get('perfil'))return [];const out=[{id:'relato-dica:demo',tipo:'dica',titulo:'Seu relato de 28/09 pode ficar mais completo',texto:'Falta: encaminhamento.',registroId:'demo',qualidade:QUALm(['encaminhamento'])}];(window.CPT_DEV?window.CPT_DEV.lista:[]).filter(d=>d.situacao==='aberta').forEach(d=>out.push({id:'devolutiva:'+d.registroId,tipo:'devolutiva',titulo:'A gestão comentou seu relato de 28/09',texto:d.atividade,devolutiva:d}));return out;};
const QUALm=f=>({itens:[['oque','O quê'],['onde','Onde'],['publico','Público'],['resultado','Resultado'],['encaminhamento','Encaminhamento'],['tamanho','Tamanho']].map(([chave,nome])=>({chave,nome,dica:'Dica de '+nome.toLowerCase()+'.',ok:!f.includes(chave)})),faltam:f.length});
const missoesO=()=>gerO()?[...(ODD.conf[hojeO]?[]:[{id:'obras-hoje',titulo:'Confirmar as obras de hoje',texto:'Marque as obras com frente de serviço hoje. Sem isso, o dia fica "não informado" no painel.',rota:'obras',aba:'hoje'}]),...(ODD.vinc.length?[{id:'vincular-obra',titulo:'Vincular '+ODD.vinc.length+' registro de "outra obra"',texto:'Ligue cada registro a uma obra do catálogo ou cadastre a obra nova.',rota:'obras',aba:'vincular'}]:[])]:[];
if(nome==='obrasDeHojeCPT'){const dia=(p&&p.dia)||hojeO;return {dia,hoje:hojeO,antesDoHorario:false,confirmado:ODD.conf[dia]||null,sugestao:['OBR-0117'],obras:ativasO(),podeConfirmar:gerO()};}
if(nome==='confirmarObrasDoDiaCPT'){if(!p.nenhuma&&!p.obras.length)throw new Error('Marque pelo menos uma obra ou "nenhuma obra hoje".');ODD.conf[p.dia]={dia:p.dia,obras:p.obras,nenhuma:p.nenhuma,versao:(p.versao||0)+1,por:'victor@example.com'};return {resultado:p.nenhuma?'Registrado: nenhuma obra.':p.obras.length+(p.obras.length===1?' obra confirmada':' obras confirmadas')+' (apenas nesta prévia).',confirmado:ODD.conf[p.dia]};}
const vincO=()=>obrasDemo.map(o=>({id:o.id,exibir:o.exibir||o.nome,bairros:o.bairros,situacao:o.situacao,busca:[o.nome,o.nomeUso].concat(o.apelidos||[]).filter(Boolean).join(' ')})).concat([{id:'OBR-0042',exibir:'Rede coletora Jardim Cipreste',bairros:['Jardim Cipreste'],situacao:'Finalizada',busca:'Rede coletora Jardim Cipreste Rede do Cipreste'}]).sort((a,b)=>(a.situacao==='Finalizada')-(b.situacao==='Finalizada')||a.exibir.localeCompare(b.exibir,'pt-BR'));
if(nome==='listarVinculosObraCPT')return {pendentes:ODD.vinc,totalPendentes:ODD.vinc.length,feitos:ODD.feitos||[],obras:vincO()};
if(nome==='vincularObraCPT'){const r=ODD.vinc.find(x=>x.id===p.registroId)||(ODD.feitos||[]).find(x=>x.id===p.registroId),o=vincO().find(x=>x.id===p.obraId),troca=(ODD.feitos||[]).some(x=>x.id===p.registroId);ODD.vinc=ODD.vinc.filter(x=>x.id!==p.registroId);ODD.feitos=[{...r,obraId:o.id,obra:o.exibir+' ['+o.id+']'}].concat((ODD.feitos||[]).filter(x=>x.id!==p.registroId));return {resultado:(troca?'Vínculo trocado para ':'Registro vinculado a ')+o.exibir+' (apenas nesta prévia).'};}
// 2.36: alertas da gestão (mesmo formato do servidor); viram missões para a gerência e o cartão da Visão do mês.
const ALERTAS_G=()=>gerO()?[{id:'casos-30',nivel:'alto',titulo:'1 atendimento em aberto há mais de 30 dias',texto:'Veja a próxima ação de cada um ou registre por que continua em aberto.',rota:'atendimentos'},
  {id:'dias-sem-acao',nivel:'medio',titulo:'2 dias úteis sem ação em outubro',texto:'01/10, 05/10. Se houve ação, confira se o relato foi enviado com a data certa.',rota:'inicio'},
  {id:'obras-ontem',nivel:'medio',titulo:'1 obra confirmada ontem sem relato',texto:'Viela Carijós. Confira se a ação aconteceu e se o relato foi enviado.',rota:'painel',aba:'frentes'},
  {id:'sem-publico',nivel:'baixo',titulo:'2 ações sem público informado',texto:'O total de pessoas alcançadas fica menor. Complete o público nos registros.',rota:'registros',pendente:'publico'}]:[];
if(nome==='alertasGestaoCPT')return {alertas:ALERTAS_G()};
if(nome==='missoesCPT')return {missoes:missoesO().concat(ALERTAS_G().map(a=>({id:'alerta:'+a.id,titulo:a.titulo,texto:a.texto,rota:a.rota,aba:a.aba,pendente:a.pendente,tipo:a.pendente?'pendente':'rota'})),missoesExtra())};
if(nome==='compararObrasDoMesCPT'){const mes=p,dias=[];const ult=new Date(Date.UTC(+mes.slice(0,4),+mes.slice(5,7),0)).getUTCDate();for(let i=1;i<=ult;i++){const dia=mes+'-'+String(i).padStart(2,'0');if(dia>hojeO)break;const c=ODD.conf[dia],demo=i%4===1?null:{obras:['OBR-0117','OBR-0074'],nenhuma:false};const k=c||demo;dias.push({dia,informado:!!k,nenhuma:!!(k&&k.nenhuma),ativas:k?k.obras.length:0,comAcao:k?Math.min(2,(i%3)):0,ativasSemAcao:k&&i%3===0?['Orquídea']:[],acaoForaDasAtivas:k&&i%5===0?['Rede Nova (demo)']:[]});}
  const inf=dias.filter(d=>d.informado);return {dias,mes:{diasInformados:inf.length,diasNaoInformados:dias.length-inf.length,ativasSemAcao:inf.reduce((s,d)=>s+d.ativasSemAcao.length,0),acaoForaDasAtivas:inf.reduce((s,d)=>s+d.acaoForaDasAtivas.length,0)}};}
if(nome==='listarObrasCPT')return {gerencia:gerO(),obras:obrasDemo,bairros:bairrosDemo.map(b=>b.nome),bairrosCadastro:bairrosDemo,situacoes:['Em andamento','Paralisada','Finalizada','A confirmar'],impactos:['Alto','Médio','Baixo'],podeEditar:!new URLSearchParams(location.search).get('perfil'),formulario:{situacao:'ok',texto:'Salvo! 12 obras + 2 opções especiais.'}};
if(nome==='salvarObraCPT'){const o={...(obrasDemo.find(x=>x.id===p.id)||{}),...p,id:p.id||'OBR-0'+(200+obrasDemo.length),atualizadoEm:new Date().toISOString(),noFormularioAgora:p.noFormulario,exibir:p.nomeUso||p.nome};obrasDemo=obrasDemo.filter(x=>x.id!==o.id).concat([o]);return {resultado:'Obra salva apenas nesta prévia.',obra:o};}
if(nome==='confirmarObraCPT'){const o=obrasDemo.find(x=>x.id===p.id);o.atualizadoEm=new Date().toISOString();return {resultado:'Situação confirmada hoje.',obra:o};}
if(nome==='carregarInicioCPT')return {perfil:perfilDemo,comparacao:{anterior:42,mesAnterior:'2026-08'},satisfacao:{mes:44,meta:60,semana:null},conta:'Prévia demonstrativa',atualizadoEm:new Date().toISOString(),mes:(p&&p.mes)||p,indicadores:{registros:54,participacoes:249,acoes:38,pessoas:412,frentes:7,diagnosticos:2,bairros:5,abertos:5,concluidos:2,recebidasNoMes:4,concluidosNoMes:3,relatosSemPublico:3,frase:'Foram contabilizadas 38 ações socioambientais, totalizando 412 pessoas alcançadas.'},destinos:[{item:'2',titulo:'Diagnóstico das áreas de trabalho',tipo:'diagnostico',quantidade:2,prontos:1},{item:'4.1',titulo:'Reuniões, grupos de discussão e fóruns periódicos',tipo:'relato',quantidade:1,prontos:1},{item:'4.2',titulo:'Ações sob eixo de gestão de resíduos sólidos',tipo:'relato',quantidade:2,prontos:0},{item:'4.3',titulo:'Ações preventivas às doenças de veiculação hídrica',tipo:'relato',quantidade:0,prontos:0},{item:'4.4',titulo:'Ações de Educação Socioambiental',tipo:'relato',quantidade:1,prontos:0},{item:'4.5',titulo:'Governança Colaborativa',tipo:'relato',quantidade:0,prontos:0},{item:'7',titulo:'Atividades da Unidade Móvel Socioambiental (UMS)',tipo:'relato',quantidade:3,prontos:1},{item:'9',titulo:'Atividades Complementares (DDS, treinamentos e campanhas internas)',tipo:'relato',quantidade:4,prontos:2},{item:'3',titulo:'Atividades desenvolvidas no período (tabela e fotos por frente)',tipo:'consolidado',quantidade:27,prontos:0}],procedimentos:[{nome:'Relato de atividade',quantidade:31},{nome:'Pesquisa de Satisfação',quantidade:12},{nome:'Acompanhamento de Vistoria Cautelar',quantidade:7},{nome:'Diagnóstico de Área',quantidade:4}],dias:[2,3,4,7,8,9,10,11,14,15,16,17,18,21,22,23,24,25,28].map((v,i)=>({data:'2026-09-'+String(v).padStart(2,'0'),quantidade:i===0?1:[2,4,3,1,5][i%5],pessoas:i===0?8:[18,52,30,6,71][i%5]})),recentes:registros.slice(0,5),filtros:{obras:['Frente de obra demonstrativa'],procedimentos:['Relato de atividade','Pesquisa de Satisfação'],bairros:['Vila Linda','Jardim do Estádio','Vila Assunção']},links:{}};
if(nome==='buscarRegistrosCPT'){const rows=registros.filter(r=>(!p.busca||JSON.stringify(r).toLowerCase().includes(p.busca.toLowerCase()))&&(!p.procedimento||r.procedimento===p.procedimento)&&(!p.bairro||r.bairro===p.bairro)&&p.mes==='2026-09');const start=Number(p.cursor||0);return {itens:rows.slice(start,start+50),proximoCursor:start+50<rows.length?String(start+50):null};}
if(nome==='abrirRegistroCPT')return {registro:registros.find(r=>r.id===p),anexos:[],campos:[{titulo:'Como foi a atividade?',valor:'A equipe conversou com os moradores sobre o andamento da obra e registrou as dúvidas para acompanhamento. Este texto é apenas demonstrativo.'},{titulo:'Participantes informados',valor:18}]};
if(nome==='buscarAtendimentosCPT'){const bc=(p.busca||'').trim().toLowerCase().match(/^(?:caso\s*|#\s*)?0*(\d{1,4})$/);const rows=casos.filter(r=>(!p.estado||(p.estado==='concluidos')===r.concluido)&&(!p.busca||(bc?Number(r.protocolo.slice(-4))===Number(bc[1]):JSON.stringify(r).toLowerCase().includes(p.busca.toLowerCase()))));return {itens:rows,total:rows.length,proximaPagina:null};}
if(nome==='abrirAtendimentoCPT'){const papel=new URLSearchParams(location.search).get('perfil'),conduz=!papel||['atendimento','comunicacao','gestao','administrativo'].includes(papel),exec=conduz||papel==='gestao';window.CPT_ESTADO=window.CPT_ESTADO||{};const st=window.CPT_ESTADO[p]||{};const f={...casos.find(r=>r.protocolo===p),...st.ficha};
  return {ficha:f,protocoloConsultado:p,procedencia:st.procedencia||'Em análise',versao:st.versao||'v1',abertura:{tipo:'Reclamação',canal:'Atendimento itinerante',urgencia:'Média',solicitacao:'Relato fictício: saída de lama na calçada após a obra.',telefone:'(11) 0000-0000',contatoOculto:false,registroId:''},opcoes:{status:['Recebida','Em andamento','Concluída'],procedencias:['Em análise','Procedente','Não procedente'],areas:['Atendimento','Execução','Socioambiental','Comunicação','Gestão']},pode:{atualizar:conduz,executar:conduz,finalizar:conduz,reabrir:conduz,corrigir:conduz,incorporar:conduz,fichaOficial:conduz},correcao:conduz?{nome:f.nome,telefone:'(11) 0000-0000',email:'',endereco:f.endereco,assunto:f.assunto,tipo:'Reclamação',canal:'Atendimento itinerante',local:'',solicitacao:'Relato fictício: saída de lama na calçada após a obra.'}:null,fichaAtualizada:!!st.fichaOk};}
if(nome==='gerarFichaOficialCPT'){window.CPT_ESTADO=window.CPT_ESTADO||{};const st=window.CPT_ESTADO[p.protocolo]||(window.CPT_ESTADO[p.protocolo]={ficha:{},eventos:[]});st.fichaOk=true;st.ficha.pdf='https://drive.google.com/file/d/previa/view';st.eventos.unshift({tipo:'Ficha oficial gerada',data:'agora',status:'',autor:'Prévia',resumo:'Documento e PDF no modelo oficial'});return {gerada:true,documento:'https://docs.google.com/document/d/previa/edit',pdf:st.ficha.pdf,resultado:'Ficha oficial gerada.'};}
if(nome==='estadoFichasCPT'||nome==='atualizarFichasCPT'){const F=window.FICHAS_PREVIA||(window.FICHAS_PREVIA={total:69,ok:38,gerar:7,mover:22,nCorrigir:2,naPastaAntiga:22,corrigir:[{caso:'Caso 41',protocolo:'ATD20260041'},{caso:'Caso 57',protocolo:'ATD20260057'}],pasta:'https://drive.google.com/drive/folders/previa-nova',pastaAntiga:'https://drive.google.com/drive/folders/previa-antiga',rotina:{em:'2026-10-07T03:02:00.000Z',segundos:41,passos:[{id:'fichas',nome:'Fichas oficiais',ok:true,texto:'2 gerada(s), 0 movida(s)'}]}});
  if(nome==='estadoFichasCPT')return {...F};const g=Math.min(F.gerar,5),m=Math.min(F.mover,12-g);F.gerar-=g;F.mover-=m;F.ok+=g+m;F.naPastaAntiga=Math.max(0,F.naPastaAntiga-m-(g?1:0));if(!F.gerar&&!F.mover)F.naPastaAntiga=0;return {...F,geradas:g,movidas:m,erros:[],faltam:F.gerar+F.mover};}
if(nome==='conferirAnexosCPT'||nome==='atualizarAnexosCPT'){const g=nome==='atualizarAnexosCPT';const A=window.ANEXOS_PREVIA||(window.ANEXOS_PREVIA={gravado:false});
  const L=[[9,'Maninfestações abertas',11,14,'fichas abertas no mês'],[10,'Solicitação',3,4,'fichas abertas no mês do tipo Solicitação'],[11,'Reclamação',10,8,'fichas abertas no mês do tipo Reclamação'],[12,'Elogio',5,2,'fichas abertas no mês do tipo Elogio'],[13,'Concluídas ',5,6,'fichas concluídas no mês'],[14,'Não procedente',0,1,'fichas abertas no mês com procedência "Não procedente"'],[15,'Total de parceiros',77,72,'contatos cadastrados na Matriz de Contatos desta planilha'],[28,'Total de participantes em ações de Educação Socioambiental',642,702,'pessoas alcançadas nas ações socioambientais do mês (Visão do mês)'],[29,'Total de ações socioambientais',83,86,'ações socioambientais do mês (Visão do mês)'],[31,'Total de comunicados entregues para vistoria cautelar','',7,'registros "Acompanhamento de Vistoria Cautelar" do mês'],[32,'Publicações na mídia (jornal, rádio, TV, rede social e sites)',1,3,'Materiais concluídos no mês: publicações em rede social e na mídia'],[33,'Ferramentas de comunicação social criadas',13,4,'Materiais concluídos no mês: impresso, vídeo, arte e apresentação'],[34,'Total de materias impressos entregues para a população',250,310,'panfletos entregues informados nos relatos do mês'],[43,'Outra coisa',93,96,'pessoas alcançadas nas ações do mês com Tenda/UMS como ferramenta (relatos)']];
  const feito=g||A.gravado;if(g)A.gravado=true;const linhas=L.map(([linha,rotulo,atual,valor,fonte])=>linha===43?{linha,rotulo,atual,valor,fonte,situacao:'pulada',aviso:'Rótulo diferente do esperado na linha 43: a planilha mudou? Nada foi escrito nela.'}:{linha,rotulo,atual:feito?valor:atual,valor,fonte,situacao:feito&&!g?'igual':String(atual)===String(valor)?'igual':'muda'});
  return {em:new Date().toISOString(),gravado:g,desde:'2026-10',links:{planilha:'https://docs.google.com/spreadsheets/d/previa-anexos/edit',xlsx:'https://docs.google.com/spreadsheets/d/previa-anexos/export?format=xlsx'},
    controle:feito&&!g?{casos:58,semNome:1,linhas:61,novos:[],atualizados:[],marcados:0,iguais:58,avisos:[]}:{casos:58,semNome:1,linhas:59,novos:['ATD20260061','ATD20260062'],atualizados:['ATD20260012','ATD20260031','ATD20260047'],marcados:4,iguais:49,avisos:['O caso ATD20260031 foi reaberto: na planilha volta para "Em andamento" (a linha continua no lugar).']},
    indicadores:[{mes:'2026-10',coluna:18,linhas}],ultima:feito?{em:new Date().toISOString(),novos:2,atualizados:3,avisos:1,indicadores:[]}:{em:'2026-10-07T03:01:00.000Z',novos:0,atualizados:1,avisos:0,indicadores:[]}};}
if(nome==='montarPacoteFichasCPT'){if(!/^\d{4}-\d{2}$/.test(p.mes))throw new Error('Escolha um mês válido.');return {mes:p.mes,pasta:'https://drive.google.com/drive/folders/previa-pacote',casos:23,grupos:{'Aberto no mês':9,'Concluído no mês':6,'Em andamento':8},copiadas:21,iguais:0,pendentes:2,faltam:0,geradas:3,movidas:0,erros:[],completo:false};}
if(['atualizarAtendimentoCPT','registrarExecucaoCPT','finalizarAtendimentoCPT','reabrirAtendimentoCPT','corrigirAtendimentoCPT','incorporarAtendimentoCPT'].includes(nome)){window.CPT_ESTADO=window.CPT_ESTADO||{};const st=window.CPT_ESTADO[p.protocolo]||(window.CPT_ESTADO[p.protocolo]={ficha:{},eventos:[]});const v='v'+(Number(String(st.versao||'v1').slice(1))+1);
  const muda={atualizarAtendimentoCPT:{status:p.status,area:p.area,proximaAcao:p.proximaAcao},registrarExecucaoCPT:{status:'Em andamento',proximaAcao:'Conferir execução e finalizar ficha'},finalizarAtendimentoCPT:{status:'Concluída',concluido:true,conclusao:p.data},reabrirAtendimentoCPT:{status:'Em andamento',concluido:false,conclusao:'',proximaAcao:p.proximaAcao},corrigirAtendimentoCPT:{nome:p.dados&&p.dados.nome},incorporarAtendimentoCPT:{}}[nome];
  Object.assign(st.ficha,muda);st.versao=v;if(p.procedencia)st.procedencia=p.procedencia;st.eventos.unshift({tipo:{atualizarAtendimentoCPT:'Atualização',registrarExecucaoCPT:'Execução',finalizarAtendimentoCPT:'Finalização',reabrirAtendimentoCPT:'Reabertura',corrigirAtendimentoCPT:'Correção de ficha',incorporarAtendimentoCPT:'Vínculo de protocolos'}[nome],data:'agora',status:muda.status,autor:'Prévia',resumo:p.feito||p.conclusao||p.motivo||p.proximaAcao||''});
  return {resultado:'Registrado apenas nesta prévia.',versao:v};}
if(nome==='carregarCronogramaCPT')return {itens:eventosDemo.filter(e=>e.data.startsWith(p.mes)),pessoas:equipeDemo,perfil:perfilDemo};
if(nome==='salvarAtividadeCPT'){const e={...p,id:p.id||'AG-'+crypto.randomUUID(),versao:Number(p.versao||0)+1,podeEditar:true,alteradoPor:perfilDemo.email};eventosDemo=eventosDemo.filter(x=>x.id!==e.id).concat([e]);return {resultado:'Salvo apenas nesta prévia. Nenhuma planilha foi alterada.',evento:e};}
if(nome==='historicoAtividadeCPT')return {versoes:eventosDemo.filter(e=>e.id===p)};
if(nome==='consultarHistoricoFichaCPT')return {itens:[...(((window.CPT_ESTADO||{})[p.protocolo]||{}).eventos||[]),{id:'MOV-demo',protocolo:p.protocolo,data:'30/09/2026 09:00',tipo:'Atualização demonstrativa',status:'Em acompanhamento',autor:'Equipe de exemplo',resumo:'Contato com o morador registrado. Dado fictício.'}],proximoCursor:null};
if(nome==='carregarPainelGestaoCPT'){const meses=['2026-04','2026-05','2026-06','2026-07','2026-08','2026-09'];return {mes:p.mes,hoje:'2026-09-30',atualizadoEm:new Date().toISOString(),
  contrato:{acoes:38,pessoas:412,semPublico:3,diagnosticos:1,frentes:7,bairros:9,pesquisas:{mes:44,meta:60,semana:{de:'2026-09-28',ate:'2026-10-04',total:6,meta:15}},relatos:{total:31,prontos:22},casos:{abertos:5,recebidosMes:6,concluidosMes:3,prazoMedio:7,acima30:1}},
  serie:meses.map((m,i)=>({mes:m,acoes:20+i*3,pessoas:150+i*40,pesquisas:30+i*3,recebidos:4+i%3,concluidos:3+i%2})),
  porItem:[{item:'4.1',titulo:'Reuniões, grupos de discussão e fóruns periódicos',quantidade:6},{item:'4.2',titulo:'Ações sob eixo de gestão de resíduos sólidos',quantidade:4},{item:'4.4',titulo:'Ações de Educação Socioambiental',quantidade:9},{item:'9',titulo:'DDS e ações complementares',quantidade:5}],
  porTipo:[{nome:'Ação Social Externa',quantidade:14},{nome:'Realização de CAO',quantidade:6},{nome:'DDS',quantidade:5}],
  frentes:[{id:'OBR-0117',nome:'Viela Sanitária x Carijós – Obra Córrego',situacao:'Em andamento',bairros:['Jardim do Estádio','Vila Linda'],endereco:'Rua fictícia, 100',impacto:'Alto',acoes:14,pessoas:160,diagnosticos:1,ultimo:'2026-09-28',diasSemRegistro:2,casosAbertos:2,casosMes:3,atividades:[{id:registros[1].id,data:'2026-09-28',atividade:'Diálogo com moradores',publico:12,responsavel:'Equipe de exemplo',bairro:'Vila Linda',diagnostico:false}],casos:[{protocolo:'ATD20260014',assunto:'Recomposição da calçada',dias:12,status:'Em andamento'}]},
    {id:'OBR-0120',nome:'Coletor tronco demonstrativo',situacao:'Em andamento',bairros:['Vila Assunção'],endereco:'',impacto:'Médio',acoes:0,pessoas:0,diagnosticos:0,ultimo:'2026-09-02',diasSemRegistro:28,casosAbertos:0,casosMes:0,atividades:[],casos:[]}],
  alertas:[{nivel:'alto',texto:'1 atendimento(s) em aberto há mais de 30 dias.',rota:'atendimentos'},{nivel:'medio',texto:'Pesquisas de satisfação nesta semana: 6 de 15.',rota:'registros'},{nivel:'medio',texto:'1 frente(s) em andamento sem registro há mais de 14 dias: Coletor tronco demonstrativo.',aba:'frentes'}],
  parceiros:{situacao:'rascunho',versao:2,conferidos:12}};}
const CRIT=[['oque','O quê','Diga que atividade foi feita e com que tema.'],['onde','Onde','Informe o local, além do bairro.'],['publico','Público','Quem participou e quantas pessoas.'],['resultado','Resultado','Conte o que aconteceu.'],['encaminhamento','Encaminhamento','O que fica para depois.'],['tamanho','Tamanho','Ao menos 5 linhas.']];
const QUAL=falta=>({itens:CRIT.map(([chave,nome,dica])=>({chave,nome,dica,ok:!falta.includes(chave)})),faltam:falta.length});
window.CPT_DEV=window.CPT_DEV||{lista:[],vistaDica:false};
if(nome==='minhasDevolutivasCPT')return {devolutivas:window.CPT_DEV.lista,podeDevolver:!new URLSearchParams(location.search).get('perfil'),criterios:CRIT};
if(nome==='devolverRelatoCPT'){const d={registroId:p.registroId,data:'2026-09-28',atividade:'Diálogo com moradores',comentario:p.comentario,situacao:'aberta',resposta:'',autor:'victor@example.com',autorNome:'Equipe de exemplo',por:'victor@example.com',versao:1};window.CPT_DEV.lista=window.CPT_DEV.lista.filter(x=>x.registroId!==p.registroId).concat([d]);return {resultado:'Comentário enviado só para quem escreveu (prévia).',devolutiva:d};}
if(nome==='responderDevolutivaCPT'){const d=window.CPT_DEV.lista.find(x=>x.registroId===p.registroId);d.situacao='vista';d.resposta=p.resposta;return {resultado:'Marcado como visto.',devolutiva:d};}
// 2.34: ferramenta Relatos. Perfil simulado: o proprietário (Victor Xavier) e a gestão veem os pontos de todos; os demais, só dos relatos de que participaram.
if(nome==='carregarRelatosCPT'){const forced=new URLSearchParams(location.search).get('perfil'),ger=!forced||['gestao','administrativo'].includes(forced),eu=forced==='socioambiental'?'Equipe social de exemplo':perfilDemo.nome;
  const PT={oque:['O quê','Diga que atividade foi feita e com que tema.'],onde:['Onde','Informe o local: rua, escola, praça ou equipamento.'],resultado:['Resultado','Conte o que aconteceu: dúvidas, o que as pessoas entenderam.'],encaminhamento:['Encaminhamento','O que fica para depois ou "sem encaminhamentos".'],tamanho:['Tamanho','Escreva ao menos 5 linhas.']};
  const base=[{id:registros[1].id,data:'2026-09-28',atividade:'Diálogo com moradores',bairro:'Vila Linda',frente:'Viela Carijós',responsavel:'Equipe social de exemplo',apoio:'Victor Xavier',publico:12,fotos:3,resumo:'A equipe conversou com moradores sobre o andamento da obra e registrou dúvidas. Texto demonstrativo.',falta:['encaminhamento']},
    {id:registros[2].id,data:'2026-09-27',atividade:'Sensibilização em frente de obra',bairro:'Vila Assunção',frente:'',responsavel:'Comunicadora de exemplo',apoio:'',publico:null,fotos:0,resumo:'',falta:['resultado','encaminhamento','tamanho']},
    {id:registros[4].id,data:'2026-09-25',atividade:'Roda de conversa na escola',bairro:'Jardim do Estádio',frente:'',responsavel:'Victor Xavier',apoio:'Equipe social de exemplo, Comunicadora de exemplo',publico:40,fotos:5,resumo:'Roda de conversa com alunos sobre o caminho do esgoto até a estação. Texto demonstrativo.',falta:[]}];
  const nm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),itens=base.map(({falta,...r})=>{const meu=nm(r.responsavel)===nm(eu)||r.apoio.split(/\s*,\s*/).map(nm).includes(nm(eu));return {...r,meu,pontos:meu||ger?falta.map(k=>({nome:PT[k][0],dica:PT[k][1]})):null,devolutiva:null};});
  return {mes:p.mes,itens,gerencia:ger,bairros:[...new Set(itens.map(x=>x.bairro))].sort()};}
if(nome==='qualidadeRelatosCPT')return {mes:p.mes,meses:[['2026-04',0,0],['2026-05',12,5],['2026-06',18,9],['2026-07',22,13],['2026-08',25,17],['2026-09',20,15]].map(([mes,total,completos])=>({mes,total,completos})),total:20,completos:15,
  faltas:[['encaminhamento','Encaminhamento',4],['publico','Público',3],['tamanho','Tamanho',2],['onde','Onde',1],['resultado','Resultado',0],['oque','O quê',0]].map(([chave,nome,quantidade])=>({chave,nome,quantidade})),
  frentes:[{nome:'Viela Carijós',total:9,completos:8},{nome:'Coletor tronco A',total:7,completos:5},{nome:'Sem frente informada',total:4,completos:2}]};
if(nome==='abrirNoRdasCPT')return {url:'https://docs.google.com/spreadsheets/d/previa/edit#gid=1&range=A40',achou:true,texto:'Ficha do relato no RDAS.'};
if(nome==='carregarRelatosResumoCPT')return ((r)=>{r.itens.forEach((x,i)=>{if(/relato de atividade/i.test(x.procedimento))x.qualidade=QUAL(i===0?['encaminhamento']:['resultado','encaminhamento','tamanho']);});return r;})({mes:p,itens:[{id:registros[1].id,data:'2026-09-28',atividade:'Diálogo com moradores',procedimento:'Relato de atividade',bairro:'Vila Linda',frente:'Viela Sanitária x Carijós',responsavel:'Equipe de exemplo',publico:12,item:'4.4',resumo:'A equipe conversou com moradores sobre o andamento da obra e registrou dúvidas. Texto demonstrativo.',objetivo:'Informar sobre a obra.',fotos:3,situacao:'pronto'},{id:registros[2].id,data:'2026-09-27',atividade:'Sensibilização em frente de obra',procedimento:'Relato de atividade',bairro:'Vila Assunção',frente:'',responsavel:'Equipe de exemplo',publico:null,item:'3',resumo:'',objetivo:'',fotos:0,situacao:''}]});
if(nome==='conferirConectoresCPT')return {travada:true,conectores:[{chave:'parceiros',nome:'Máscara do Programa Parceiros',tipo:'planilha',uso:'A Gestão publica aqui.',id:'x',ok:true,titulo:'Máscara de lançamento',compartilhamento:'Só o proprietário',url:'https://docs.google.com/spreadsheets/d/previa/edit'},{chave:'rdas',nome:'RDAS — relatos diários',tipo:'planilha',uso:'Planilha à parte.',id:'y',ok:false,erro:'Sem acesso (prévia).',url:'https://docs.google.com/spreadsheets/d/previa/edit'}],
  pastas:[{id:'f1',nome:'Fotos da atividade (File responses)',url:'https://drive.google.com/drive/folders/previa',motivo:'Fotos e arquivos enviados pelo formulário',arquivos:12,equipeVe:false,texto:'Só o proprietário'},{id:'f2',nome:'CPT • Entregas mensais',url:'https://drive.google.com/drive/folders/previa2',motivo:'Relatórios, anexos, fichas e Programa Parceiros gerados pela aplicação',arquivos:1,equipeVe:true,texto:'Compartilhada com o domínio (leitura)'}]};
if(nome==='configurarConectorCPT')return {resultado:'Conector atualizado (prévia).'};
if(nome==='auditarAtendimentosCPT'){const it=(pr,det)=>({protocolo:pr,nome:'Pessoa de exemplo',assunto:'Recomposição da calçada',dias:35,area:'Execução',status:'Em andamento',detalhe:det});return {hoje:'2026-09-30',pendencias:2,atualizadoEm:new Date().toISOString(),
  verificacoes:[{id:'recebidaParada',titulo:'Recebidos sem nenhuma ação há mais de 3 dias',ajuda:'Faça a triagem.',grave:true,quantidade:1,itens:[it('ATD20260015','5 dias como Recebida')]},{id:'prazo',titulo:'Em aberto há mais de 30 dias',ajuda:'Confira com a área.',grave:true,quantidade:1,itens:[it('ATD20260014','35 dias em aberto')]},{id:'semFicha',titulo:'Sem ficha oficial em PDF',ajuda:'Gere a ficha.',quantidade:0,itens:[]}],
  numeros:{abertos:5,concluidos:2,total:7,prazoMedio:7,porMes:['2026-04','2026-05','2026-06','2026-07','2026-08','2026-09'].map((m,i)=>({mes:m,recebidos:3+i%3,concluidos:2+i%2})),porArea:[{nome:'Execução',quantidade:3},{nome:'Atendimento',quantidade:2}],porIdade:[{nome:'Até 7 dias',quantidade:2},{nome:'Mais de 30 dias',quantidade:1}],porTipo:[{nome:'Reclamação',quantidade:3},{nome:'Solicitação',quantidade:2}],porCanal:[{nome:'Atendimento itinerante',quantidade:4}],maisAntigos:[it('ATD20260014','35 dias')]}};}
if(!window.CPT_COM){const h=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date()),mais=n=>{const d=new Date(h+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
  window.CPT_COM={hoje:h,mais,recados:[{id:'REC-1',versao:1,para:{frentes:['comunicacao'],pessoas:[]},assunto:'Fotos da oficina de horta',texto:'Consegue separar 6 fotos da oficina para o relatório? (exemplo)',importante:true,prazo:mais(2),vinculo:{tipo:'registro',id:registros[1].id,titulo:'Oficina de horta',url:''},situacao:'aberto',respostas:[],lidos:{},nomeAutor:'Equipe social de exemplo',criadoPor:'social@example.com',criadoEm:new Date().toISOString(),atualizadoEm:new Date().toISOString()}],
  contatos:[{id:'CON-1',versao:1,nome:'Diretora de exemplo',instituicao:'EMEIEF fictícia',tipo:'Equipamento público (escola, UBS, CRAS)',telefone:'(11) 90000-0000',email:'escola@example.com',endereco:'',bairro:'Vila Linda',frente:'',etiquetas:'escola, horta',observacao:'Prefere contato pela manhã.',cor:'verde',registros:[{em:mais(-3),canal:'Telefone',texto:'Combinada oficina para a próxima semana.',nome:'Equipe social de exemplo'}],criadoPor:'social@example.com'}],
  lembretes:[{id:'LEM-1',versao:1,criadoPor:'victor@example.com',nomeAutor:'Victor Xavier',tipo:'material',titulo:'Levar 200 panfletos da obra',data:h,detalhe:'',material:'200 panfletos',frentes:['socioambiental','comunicacao'],responsavel:'paula@example.com',evento:null,situacao:'pendente'},{id:'LEM-2',versao:1,criadoPor:'paula@example.com',nomeAutor:'Comunicadora de exemplo',tipo:'acao',titulo:'Divulgar a ação de óleo',data:mais(-1),detalhe:'',material:'',frentes:['comunicacao'],responsavel:'',evento:null,situacao:'pendente'},{id:'LEM-3',versao:1,tipo:'acao',titulo:'Ação na feira',data:mais(4),detalhe:'',material:'',frentes:['socioambiental','comunicacao'],responsavel:'',evento:null,situacao:'pendente'}],
  materiais:[{id:'MAT-1',versao:1,titulo:'Post sobre a obra da viela',url:'https://www.instagram.com/',tipo:'Publicação em rede social',observacao:'Aguardando aprovação.',canal:'',responsavel:'paula@example.com',prazo:mais(1),situacao:'producao',publicadoEm:'',alcance:null,quantidade:null},{id:'MAT-2',versao:1,titulo:'Vídeo da oficina de horta',url:'',tipo:'Vídeo',observacao:'',canal:'Instagram',responsavel:'',prazo:'',situacao:'concluido',publicadoEm:'2026-09-10',alcance:null,quantidade:null},{id:'MAT-3',versao:1,titulo:'Matéria no jornal do bairro',url:'',tipo:'Matéria na mídia (jornal, rádio, TV, site)',observacao:'',canal:'Jornal local',responsavel:'',prazo:'',situacao:'concluido',publicadoEm:'2026-09-12',alcance:5000,quantidade:null}],
  extras:[]};}
const COM=window.CPT_COM,pessoasCom=equipeDemo.map(x=>({email:x.email,nome:x.nome,papeis:x.papeis}));
const tiposMat=['Publicação em rede social','Matéria na mídia (jornal, rádio, TV, site)','Material impresso','Vídeo','Arte / peça digital','Apresentação','Referência / pasta de arquivos','Outro'];
const resumoMat=mes=>{const f=COM.materiais.filter(m=>m.situacao==='concluido'&&String(m.publicadoEm||m.prazo).slice(0,7)===mes),pub=f.filter(m=>m.tipo===tiposMat[0]||m.tipo===tiposMat[1]);return {mes,concluidos:f.length,publicacoes:pub.length,alcance:pub.reduce((a,m)=>a+(m.alcance||0),0),semAlcance:pub.filter(m=>m.alcance==null).length,temas:pub.map(m=>m.titulo),impressos:f.filter(m=>m.tipo===tiposMat[2]).reduce((a,m)=>a+(m.quantidade||0),0),videos:f.filter(m=>m.tipo===tiposMat[3]).length,ferramentas:f.filter(m=>[2,3,4,5].some(i=>m.tipo===tiposMat[i])).length};};
const pubRec=r=>({...r,paraMim:r.para.frentes.some(f=>perfilDemo.papeis.includes(f))||r.para.pessoas.includes(perfilDemo.email),lido:!!r.lidos[perfilDemo.email],meu:r.criadoPor===perfilDemo.email});
const NOMESF={atendimento:'Atendimento',socioambiental:'Socioambiental',comunicacao:'Comunicação',comercializacao:'Comercialização',gestao:'Gestão',administrativo:'Administrativo'},nomeP=e=>(pessoasCom.find(x=>x.email===e)||{nome:e?e.split('@')[0]:''}).nome;
const lemPara=l=>l.responsavel?l.responsavel===perfilDemo.email:(l.frentes||[]).some(f=>perfilDemo.papeis.filter(x=>x!=='administrador').includes(f));
const lemDia=dia=>COM.lembretes.filter(l=>(lemPara(l)||l.criadoPor===perfilDemo.email)&&(l.data===dia||(dia===COM.hoje&&l.data<COM.hoje&&l.situacao!=='feito'))).map(l=>({id:l.id,titulo:l.titulo,data:l.data,feito:l.situacao==='feito',feitoPor:l.feitoPor?nomeP(l.feitoPor):'',meu:l.feitoPor===perfilDemo.email,atrasado:l.data<COM.hoje&&l.situacao!=='feito',de:l.criadoPor&&l.criadoPor!==perfilDemo.email?(l.nomeAutor||nomeP(l.criadoPor)):'',para:lemPara(l)?'':(l.responsavel?nomeP(l.responsavel):(l.frentes||[]).map(f=>NOMESF[f]).join(', '))}));
const lemPendentes=()=>COM.lembretes.filter(l=>lemPara(l)&&l.situacao!=='feito'&&l.data<=COM.hoje).length;
const naoLidos=()=>COM.recados.filter(r=>pubRec(r).paraMim&&!r.lidos[perfilDemo.email]&&r.criadoPor!==perfilDemo.email&&r.situacao!=='resolvido');
const upd=(lista,item,pref)=>{const i=lista.findIndex(x=>x.id===item.id);const novo={...(i>=0?lista[i]:{}),...item,id:item.id||pref+'-'+crypto.randomUUID().slice(0,8),versao:(i>=0?lista[i].versao:0)+1,criadoPor:i>=0?lista[i].criadoPor:perfilDemo.email,criadoEm:i>=0?lista[i].criadoEm:new Date().toISOString()};if(i>=0)lista[i]=novo;else lista.push(novo);return novo;};
if(nome==='contarAvisosCPT')return {recados:naoLidos().length,lembretes:lemPendentes()};
if(nome==='listarRecadosCPT')return {itens:COM.recados.map(pubRec),pessoas:pessoasCom,naoLidos:naoLidos().length};
if(nome==='enviarRecadoCPT'){if(!p.assunto||!p.texto)throw new Error('Preencha: assunto.');if(!p.para.frentes.length&&!p.para.pessoas.length)throw new Error('Escolha para quem vai o recado (uma frente ou uma pessoa).');const r=upd(COM.recados,{...p,situacao:'aberto',respostas:[],lidos:{[perfilDemo.email]:1},nomeAutor:perfilDemo.nome,atualizadoEm:new Date().toISOString()},'REC');return {resultado:'Recado enviado. (prévia)',recado:pubRec(r)};}
if(nome==='agirRecadoCPT'){const r=COM.recados.find(x=>x.id===p.id);if(p.acao==='lido')r.lidos[perfilDemo.email]=1;if(p.acao==='responder'){r.respostas.push({nome:perfilDemo.nome,em:new Date().toISOString(),texto:p.texto});r.lidos={[perfilDemo.email]:1};}if(p.acao==='resolver')r.situacao='resolvido';if(p.acao==='reabrir')r.situacao='aberto';r.atualizadoEm=new Date().toISOString();return {resultado:'Feito (prévia).',recado:pubRec(r)};}
// 2.40: Matriz Sabesp (dados fictícios). ?matriz=nova simula antes da importação.
const MAT=window.MAT_PREVIA||(window.MAT_PREVIA={importada:new URLSearchParams(location.search).get('matriz')!=='nova',itens:[]});
const matPapel=()=>{const p=new URLSearchParams(location.search).get('perfil');return !p||['gestao','administrativo'].includes(p);};
const matEv=(acao,detalhe)=>({em:new Date().toISOString(),por:'victor@example.com',nome:'Victor (prévia)',acao,detalhe:detalhe||''});
const matSecoes=['REGIÃO/LOCALIDADE · LIDERANÇAS LOCAIS','SECRETARIAS DE GOVERNO','ESCOLAS MUNICIPAIS E ESTADUAIS','ENTIDADES RELIGIOSAS','VEÍCULOS DE IMPRENSA'];
const matSemente=()=>{if(MAT.itens.length||!MAT.importada)return;[['Associação de Moradores Fictícia','Pessoa A','(11) 90000-0001',0],['Coletivo Cultural Fictício','Pessoa B','(11) 90000-0002',0],['Secretaria Fictícia de Meio Ambiente','Pessoa C','(11) 4000-0003',1],['EMEF Fictícia','Diretora D','(11) 4000-0004',2],['Paróquia Fictícia','Pessoa E','',3],['Rádio Comunitária Fictícia','Pessoa F','(11) 4000-0006',4]].forEach(([nome,pessoa,telefone,s],i)=>MAT.itens.push({id:'MSP-'+i,versao:1,secao:matSecoes[s],nome,pessoa,telefone,email:'',endereco:'',observacao:'',atualizacao:'2026-09-01',ativo:true,situacao:'aprovado',proposta:null,aGravar:false,erroPlanilha:'',historico:[matEv('Importado da planilha','linha '+(5+i))]}));
  MAT.itens.push({id:'MSP-p1',versao:1,secao:matSecoes[0],nome:'',pessoa:'',telefone:'',email:'',endereco:'',observacao:'',atualizacao:'',ativo:true,situacao:'pendente',proposta:{tipo:'novo',secao:matSecoes[0],campos:{nome:'Horta Comunitária Fictícia',pessoa:'Pessoa G',telefone:'(11) 90000-0007',email:'',endereco:'',observacao:''},por:'social@example.com',nome:'Social (prévia)',em:'2026-10-06T14:00:00.000Z',motivo:''},aGravar:false,erroPlanilha:'',historico:[matEv('Proposto','Contato novo')]});
  const b=MAT.itens[1];b.proposta={tipo:'alteracao',campos:{nome:b.nome,pessoa:'Pessoa B2',telefone:'(11) 90000-0022',email:'',endereco:'',observacao:''},por:'social@example.com',nome:'Social (prévia)',em:'2026-10-06T15:00:00.000Z',motivo:''};b.versao=2;};
if(nome==='listarMatrizCPT'){matSemente();return {itens:MAT.itens.filter(c=>c.situacao!=='recusado').map(c=>({...c})),secoes:matSecoes,importada:MAT.importada,podeAprovar:matPapel(),campos:{nome:'Nome / função / cargo',pessoa:'Pessoa de contato',endereco:'Endereço',telefone:'Telefone',email:'E-mail',observacao:'Observação'}};}
if(nome==='importarMatrizCPT'){MAT.importada=true;matSemente();return {resultado:MAT.itens.length+' contatos importados de 5 seções.',importados:MAT.itens.length,secoes:5};}
if(nome==='proporMatrizCPT'){const pr={tipo:p.tipo,por:'victor@example.com',nome:'Victor (prévia)',em:new Date().toISOString(),motivo:p.motivo||''};
  if(p.tipo==='novo'){if(!p.secao)throw new Error('Escolha a seção da Matriz.');pr.secao=p.secao;pr.campos={nome:p.nome,pessoa:p.pessoa||'',telefone:p.telefone||'',email:p.email||'',endereco:p.endereco||'',observacao:p.observacao||''};const c={id:'MSP-n'+MAT.itens.length,versao:1,secao:p.secao,nome:'',pessoa:'',telefone:'',email:'',endereco:'',observacao:'',atualizacao:'',ativo:true,situacao:'pendente',proposta:pr,aGravar:false,erroPlanilha:'',historico:[matEv('Proposto','Contato novo em '+p.secao)]};MAT.itens.push(c);return {resultado:'Contato proposto. Ele entra na Matriz quando a Gestão ou o Administrativo aprovar.',contato:{...c}};}
  const c=MAT.itens.find(x=>x.id===p.id);if(p.tipo==='inativar'&&!p.motivo)throw new Error('Preencha: motivo.');if(p.tipo==='alteracao')pr.campos={nome:p.nome,pessoa:p.pessoa||'',telefone:p.telefone||'',email:p.email||'',endereco:p.endereco||'',observacao:p.observacao||''};c.proposta=pr;c.versao++;c.historico.push(matEv('Proposto',p.tipo));return {resultado:'Proposta enviada para aprovação da Gestão ou do Administrativo.',contato:{...c}};}
if(nome==='decidirMatrizCPT'){const c=MAT.itens.find(x=>x.id===p.id),pr=c.proposta;c.versao++;c.proposta=null;
  if(p.decisao!=='aprovar'){if(!p.motivo)throw new Error('Preencha: motivo da recusa.');if(pr.tipo==='novo')c.situacao='recusado';c.historico.push(matEv('Recusado',p.motivo));return {resultado:'Proposta recusada. O motivo ficou no histórico.',contato:{...c}};}
  if(pr.campos)Object.assign(c,pr.campos);if(pr.secao)c.secao=pr.secao;c.situacao='aprovado';c.atualizacao=new Date().toISOString().slice(0,10);if(pr.tipo==='inativar'){c.ativo=false;c.observacao='Inativo desde hoje. '+pr.motivo+'.';}if(pr.tipo==='reativar'){c.ativo=true;c.observacao='';}
  c.historico.push(matEv('Aprovado',({novo:'Contato novo',alteracao:'Alteração',inativar:'Inativado',reativar:'Reativado'})[pr.tipo]),matEv('Gravado na Matriz','linha 12 atualizada'));return {resultado:'Aprovado e gravado na Matriz.',contato:{...c}};}
if(nome==='listarContatosCPT')return {matriz:(matSemente(),MAT.itens.filter(c=>c.situacao==='aprovado'&&c.ativo).map(c=>({id:c.id,nome:c.nome,pessoa:c.pessoa,telefone:c.telefone,email:c.email,secao:c.secao}))),itens:COM.contatos.map(c=>({...c,podeEditar:true})),tipos:['Equipe interna','Consórcio / Concrejato','Sabesp','Poder público','Equipamento público (escola, UBS, CRAS)','Liderança comunitária','Comércio','Imprensa','Morador','Fornecedor','Outro'],canais:['Telefone','WhatsApp','E-mail','Presencial','Reunião','Outro'],podeCadastrar:true};
if(nome==='salvarContatoCPT'){if(!p.nome&&!p.instituicao)throw new Error('Informe o nome da pessoa ou a instituição.');if(!p.tipo)throw new Error('Escolha uma opção válida em tipo.');const c=upd(COM.contatos,{...p,registros:(COM.contatos.find(x=>x.id===p.id)||{}).registros||[]},'CON');return {resultado:'Contato salvo. (prévia)',contato:{...c,podeEditar:true}};}
if(nome==='registrarConversaContatoCPT'){const c=COM.contatos.find(x=>x.id===p.id);c.registros=(c.registros||[]).concat([{em:p.data,canal:p.canal,texto:p.texto,nome:perfilDemo.nome}]);return {resultado:'Conversa registrada no contato.',contato:{...c,podeEditar:true}};}
if(nome==='listarLembretesCPT')return {itens:COM.lembretes.slice().sort((a,b)=>a.data.localeCompare(b.data)),pessoas:pessoasCom,hoje:COM.hoje,tipos:{acao:'Ação socioambiental',material:'Material de comunicação'}};
if(nome==='salvarLembreteCPT'){if(!p.titulo)throw new Error('Preencha: tarefa.');if(!p.responsavel&&!(p.frentes||[]).length)throw new Error('Escolha para quem é a tarefa: uma pessoa ou uma frente.');const l=upd(COM.lembretes,{...p,tipo:'acao',criadoPor:perfilDemo.email,nomeAutor:perfilDemo.nome,situacao:'pendente'},'LEM');return {resultado:'Tarefa enviada. Aparece no checklist de quem recebe, no dia marcado.',lembrete:l};}
if(nome==='concluirLembreteCPT'){const l=COM.lembretes.find(x=>x.id===p.id);l.situacao=p.feito===false?'pendente':'feito';l.feitoEm=new Date().toISOString();return {resultado:p.feito===false?'Lembrete voltou para pendente.':'Feito! Lembrete concluído.',lembrete:l};}
if(nome==='listarMateriaisCPT')return {itens:COM.materiais.filter(m=>!m.arquivado),pessoas:pessoasCom,tipos:tiposMat,situacoes:{afazer:'A fazer',producao:'Em produção',concluido:'Concluído'},resumo:resumoMat(p),hoje:COM.hoje,podeEditar:!['socioambiental','atendimento','comercializacao'].includes(new URLSearchParams(location.search).get('perfil'))};
if(nome==='salvarMaterialCPT'){if(!p.titulo)throw new Error('Preencha: título.');if(!p.tipo)throw new Error('Escolha uma opção válida em tipo.');const m=upd(COM.materiais,{...p,alcance:p.alcance?Number(p.alcance):null,quantidade:p.quantidade?Number(p.quantidade):null,publicadoEm:p.publicadoEm||(p.situacao==='concluido'?COM.hoje:'')},'MAT');return {resultado:p.situacao==='concluido'?'Material concluído e guardado no mês.':'Material salvo.',material:m};}
if(nome==='listarGaleriaCPT')return {mes:p.mes,itens:COM.extras.concat(Array.from({length:30},(_,i)=>({fileId:'FOTODEMO'+String(i).padStart(14,'0'),data:'2026-09-'+String(28-i%20).padStart(2,'0'),atividade:['Oficina de horta','Diálogo com moradores'][i%2],local:'Vila Linda',legenda:String(28-i%20).padStart(2,'0')+'/09/2026 - '+['Oficina de horta','Diálogo com moradores'][i%2]+' - Vila Linda',responsavel:'Equipe de exemplo',video:i===3,origem:'Registro',registro:registros[1].id}))),pasta:'',podeEnviar:!['atendimento','comercializacao'].includes(new URLSearchParams(location.search).get('perfil'))};
if(nome==='enviarFotoGaleriaCPT'){if(!p.atividade)throw new Error('Preencha: atividade.');const it={fileId:'EXTRA'+crypto.randomUUID().replace(/-/g,'').slice(0,20),data:p.data,atividade:p.atividade,local:p.local,legenda:p.data.split('-').reverse().join('/')+' - '+p.atividade+(p.local?' - '+p.local:''),responsavel:perfilDemo.nome,origem:'Extra',video:false};COM.extras.push(it);return {resultado:'Foto guardada na galeria.',item:it};}
if(nome==='miniaturasGaleriaCPT'){const o={};(p.ids||[]).slice(0,12).forEach(id=>{if(!/08$/.test(id))o[id]='data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="220" height="165"><rect width="220" height="165" fill="#d9a46a"/><circle cx="160" cy="50" r="22" fill="#fff8"/></svg>');});return {miniaturas:o};}
if(nome==='baixarPacoteGaleriaCPT'){if(!p.ids.length||p.ids.length>15)throw new Error('Escolha de 1 a 15 fotos para baixar.');return {nome:'Fotos '+p.mes+'.zip',base64:btoa('PK'),legendas:''};}
if(!window.CPT_ESP){window.CPT_ESP={perfil:null,notas:{},listas:{},v:0};}
const ESPdono=!new URLSearchParams(location.search).get('perfil'),ESP=window.CPT_ESP,hojeE=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date()),CAT=__CATALOGO__;
if(!ESP.quiz)ESP.quiz={dia:null,semana:[]};
const SAB=__CONTEUDO__,fonteS=k=>({nome:SAB.fontes[k][0],url:SAB.fontes[k][1],equipe:k==='equipe'}),semR=q=>({id:q.id,tema:SAB.temas[q.tema],eixo:SAB.eixos[q.eixo],pergunta:q.pergunta,opcoes:q.opcoes,revisar:true});
if(!ESP.rev)ESP.rev={};
if(nome==='carregarRevisaoConteudoCPT'){if(!ESPdono)throw new Error('Esta ação é exclusiva da administração técnica.');const base=x=>{const d=ESP.rev[x.id];return {id:x.id,tema:SAB.temas[x.tema],eixo:x.eixo,fonte:fonteS(x.fonte),situacao:d?d.situacao:'pendente',nota:d?d.nota:'',versao:d?d.versao:0,correcao:SAB.correcoes[x.id]||''};};
  const itens=SAB.curiosidades.map(c=>({...base(c),tipo:'curiosidade',texto:c.texto,importa:c.importa})).concat(SAB.perguntas.map(q=>({...base(q),tipo:'pergunta',texto:q.pergunta,opcoes:q.opcoes,certa:q.certa,explica:q.explica})));const conta=k=>itens.filter(x=>x.situacao===k).length;
  return {itens,eixos:SAB.eixos,resumo:{total:itens.length,aprovado:conta('aprovado'),suspenso:conta('suspenso'),pendente:conta('pendente'),eixos:Object.keys(SAB.eixos).map(e=>({eixo:e,nome:SAB.eixos[e],n:itens.filter(x=>x.eixo===e).length}))}};}
if(!window.CPT_ORG)window.CPT_ORG={v:0,pessoas:[['o1','Rita Exemplo','Gerente de contrato','gestao','','mar/2025'],['o2','Joana Exemplo','Coordenação socioambiental','socioambiental','o1','mai/2025'],['o3','Você (exemplo)','Assistente administrativo','administrativo','o2','ago/2025'],
  ['o4','Lia Exemplo','Comunicação','comunicacao','o2','jun/2025'],['o5','Caio Exemplo','Supervisão de atendimento','atendimento','o2','ago/2025'],['o6','Duda Exemplo','Atendimento','atendimento','o5','out/2025'],['o7','Rafa Exemplo','Supervisão de campo','campo','o2','jul/2025'],
  ['o8','Nina Exemplo','Mobilizadora','campo','o7','jul/2025'],['o9','Teo Exemplo','Mobilizador','campo','o7','jul/2025'],['o10','Gabi Exemplo','Mobilizadora','campo','o7','set/2025'],['o11','Iara Exemplo','Mobilizadora','campo','o7','set/2025'],['o12','Beto Exemplo','Agente comercial','comercializacao','o3','ago/2025']]
  .map(([id,n,c,a,ch,de],i)=>({id,versao:1,nome:n,cargo:c,area:a,chefia:ch,desde:de,ordem:0,alteradoEm:'2026-09-30T12:00:00Z'})),fora:2};
const ORGA={gestao:'Gestão',administrativo:'Administrativo',socioambiental:'Socioambiental',comunicacao:'Comunicação',atendimento:'Atendimento',comercializacao:'Comercialização',campo:'Campo e mobilização',parceiros:'Consórcio e parceiros'};
const orgCarregar=()=>({pessoas:CPT_ORG.pessoas.slice(),areas:ORGA,podeEditar:ESPdono,atualizadoEm:'2026-09-30T12:00:00Z',foraDoOrganograma:ESPdono?CPT_ORG.fora:0});
if(nome==='carregarOrganogramaCPT'){if(!ESPdono)throw new Error('O organograma está reservado à administração técnica durante o período de testes.');return orgCarregar();}
if(nome==='salvarOrganogramaCPT'){if(!ESPdono)throw new Error('Editar o organograma está reservado à administração técnica durante o período de testes.');if(!p.nome||!p.cargo)throw new Error('Preencha: nome.');
  if(p.chefia&&p.chefia===p.id)throw new Error('A pessoa não pode responder a ela mesma.');const a=CPT_ORG.pessoas.find(x=>x.id===p.id);
  if(p.ativo===false){if(CPT_ORG.pessoas.some(x=>x.chefia===p.id))throw new Error('Antes de tirar esta pessoa, mude quem responde a ela.');CPT_ORG.pessoas=CPT_ORG.pessoas.filter(x=>x.id!==p.id);return {resultado:'Pessoa tirada do organograma (fica no histórico).'};}
  const e={id:a?a.id:'o'+Date.now(),versao:(a?a.versao:0)+1,nome:p.nome,cargo:p.cargo,area:p.area,chefia:p.chefia||'',desde:p.desde||'',ordem:p.ordem||0,alteradoEm:new Date().toISOString()};
  if(a)Object.assign(a,e);else CPT_ORG.pessoas.push(e);return {resultado:'Organograma atualizado.',pessoa:e};}
if(nome==='importarOrganogramaCPT'){if(!ESPdono)throw new Error('Editar o organograma está reservado à administração técnica durante o período de testes.');const n=CPT_ORG.fora;
  for(let i=0;i<n;i++)CPT_ORG.pessoas.push({id:'oi'+i,versao:1,nome:['Ana Exemplo','Bia Exemplo'][i],cargo:'Atendimento',area:'atendimento',chefia:'',desde:'',ordem:0,alteradoEm:new Date().toISOString()});CPT_ORG.fora=0;
  return {resultado:n?n+' pessoas entraram no organograma. Agora ajuste cargo e a quem cada uma responde.':'Toda a equipe já está no organograma.',...orgCarregar()};}
if(!window.CPT_CTR)window.CPT_CTR={};
const ctrMes=(()=>{const d=new Date(hojeE.slice(0,7)+'-15T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-1);return d.toISOString().slice(0,7);})(),ctrPrazo=(()=>{const [a,m]=ctrMes.split('-').map(Number);return new Date(Date.UTC(a,m,10)).toISOString().slice(0,10);})();
const ctrNomes=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
if(nome==='controleContratoCPT'){if(!ESPdono&&!/gestao|administrativo/.test(new URLSearchParams(location.search).get('perfil')||''))throw new Error('A planilha de controle do contrato é da Gestão e do Administrativo.');const r=CPT_CTR[ctrMes];
  return {mes:ctrMes,mesNome:ctrNomes[Number(ctrMes.slice(5))-1]+' de '+ctrMes.slice(0,4),prazo:ctrPrazo,hoje:hojeE,atrasada:!(r&&r.respondida)&&hojeE>ctrPrazo,url:'https://docs.google.com/spreadsheets/d/EXEMPLO/edit#gid=1',ultimaAlteracao:'2026-10-02T13:40:00Z',respondida:r&&r.respondida?{nome:r.nome,em:r.em}:null,versao:r?r.versao:0,podeMarcar:ESPdono,
    indicadores:[['Ações socioambientais',18],['Pessoas alcançadas',412,'2 ação(ões) sem público informado'],['Frentes com atividade',6],['Bairros com ação',9],['Diagnósticos',3],['Pesquisas de satisfação',57,'meta 60'],['Atendimentos recebidos',24],['Atendimentos concluídos',19,'prazo médio 12 dias'],['Atendimentos em aberto',11,'2 há mais de 30 dias'],['Relatos prontos',14,'de 18']].map(([n,v,x])=>({nome:n,valor:v,nota:x||''}))};}
if(nome==='marcarControleContratoCPT'){if(!ESPdono)throw new Error('Marcar a planilha de controle está reservado à administração técnica durante o período de testes.');const a=CPT_CTR[p.mes];if((a?a.versao:0)!==Number(p.versao||0))throw new Error('Outra pessoa alterou este item agora há pouco.');
  const e=CPT_CTR[p.mes]={respondida:p.respondida!==false,nome:perfilDemo.nome,em:new Date().toISOString(),versao:(a?a.versao:0)+1};
  return {resultado:e.respondida?'Marcada como respondida. O lembrete deste mês some do checklist.':'Marca desfeita: o lembrete volta.',mes:p.mes,respondida:e.respondida?{nome:e.nome,em:e.em}:null,versao:e.versao};}
if(nome==='decidirConteudoCPT'){if(!ESPdono)throw new Error('Esta ação é exclusiva da administração técnica.');const a=ESP.rev[p.id];if((a?a.versao:0)!==Number(p.versao||0))throw new Error('Outra pessoa alterou este item agora há pouco. Seu texto continua na tela: atualize e confira antes de salvar de novo.');
  const e=ESP.rev[p.id]={situacao:p.situacao,nota:p.nota||'',versao:(a?a.versao:0)+1};return {resultado:{aprovado:'Aprovado.',suspenso:'Suspenso: não aparece para ninguém.',pendente:'Voltou para a revisão.'}[p.situacao],item:{id:p.id,...e}};}
const resS=r=>{const q=SAB.perguntas.find(x=>x.id===r.id);return {...semR(q),escolha:r.escolha,acertou:r.acertou,certa:q.certa,explica:q.explica,fonte:fonteS(q.fonte)};};
const QD=SAB.perguntas[(Number(hojeE.slice(8))*7)%SAB.perguntas.length],QS=SAB.perguntas.filter(q=>q.id!==QD.id).slice(10,15);
const quizPts=()=>(ESP.jog?ESP.jog.forca.concat(ESP.jog.quebra).reduce((a,x)=>a+x.pontos,0):0)+(ESP.quiz.dia&&ESP.quiz.dia.acertou?2:0)+ESP.quiz.semana.filter(r=>r.acertou).length*10;
const quizEstado=()=>{const w=ESP.quiz.semana;return {regras:{pontosDia:2,pontosPergunta:10,porSemana:5},dia:{data:hojeE,versao:ESP.quiz.dia?1:0,pergunta:ESP.quiz.dia?null:semR(QD),resposta:ESP.quiz.dia?resS(ESP.quiz.dia):null},
  semana:{semana:'atual',versao:w.length,total:5,respondidas:w.length,acertos:w.filter(r=>r.acertou).length,pontos:w.filter(r=>r.acertou).length*10,indice:w.length,proxima:w.length<5?semR(QS[w.length]):null,respostas:w.map(resS)}};};
const cur=SAB.curiosidades[Number(hojeE.slice(8))%SAB.curiosidades.length],mesN=Number(hojeE.slice(5,7));
const pubC=c=>({id:c.id,tema:SAB.temas[c.tema],eixo:SAB.eixos[c.eixo],texto:c.texto,importa:c.importa,fonte:fonteS(c.fonte),revisar:true}),curs=[0,1,2,3].map(k=>pubC(SAB.curiosidades[(Number(hojeE.slice(8))+k*7)%SAB.curiosidades.length]));
const saberE=()=>ESPdono?{curiosidade:curs[0],curiosidades:curs,mes:{campanha:SAB.campanhas[mesN-1][0],tema:SAB.campanhas[mesN-1][1],datas:SAB.datas.filter(d=>d[0]===mesN).map(([,d,t,c])=>{const x=SAB.curiosidades.find(y=>y.id===c);return {dia:d,titulo:t,texto:x.texto,fonte:fonteS(x.fonte)};})},quiz:quizEstado()}:undefined;
const espPontos=()=>{const ck=Object.values(ESP.listas).reduce((a,l)=>a+Math.min(8,l.itens.filter(t=>t.pontuado).length)*10,0),qz=quizPts(),g=ck+qz,c=ESP.perfil?ESP.perfil.compras.reduce((a,x)=>a+x.preco,0):0;return {ganhos:g,gastos:c,saldo:g-c,checklist:ck,quiz:qz};};
if(!ESP.jog)ESP.jog={forca:[],quebra:[]};
const JOG=__JOGOS__,jogEstado=()=>{const um=(j,tem,precisa)=>{const h=ESP.jog[j];return {liberado:tem>=precisa,tem,precisa,partidasHoje:h.length,limite:3,vitoriasHoje:h.filter(x=>x.situacao==='venceu').length,ganhouPontosHoje:h.some(x=>x.pontos>0),aberta:h.some(x=>x.situacao==='jogando')};};
  return {forca:um('forca',6,5),quebra:um('quebra',14+Object.values(ESP.listas).filter(l=>l.itens.some(t=>t.pontuado)).length,15),regras:{pontos:5,erros:6}};};
const jogPts=()=>ESP.jog.forca.concat(ESP.jog.quebra).reduce((a,x)=>a+x.pontos,0);
if(nome==='iniciarJogoCPT'){if(!ESPdono)throw new Error('Os joguinhos estão reservados à administração técnica durante o período de testes.');const e=jogEstado()[p.jogo];if(!e.liberado)throw new Error(p.jogo==='forca'?'A forca libera com 5 dias de checklist.':'O quebra-cabeça libera com 15 dias de checklist (você tem '+e.tem+').');
  let x=ESP.jog[p.jogo].find(y=>y.situacao==='jogando');if(!x){if(e.partidasHoje>=3)throw new Error('Você já jogou 3 partidas hoje. Amanhã tem mais!');const n=ESP.jog[p.jogo].length;
    x={id:'JOG-'+p.jogo+'-'+n,jogo:p.jogo,n:n+1,situacao:'jogando',pontos:0,palavra:JOG.palavras[(n*7+3)%JOG.palavras.length],ordem:[[4,0,7,2,8,1,6,3,5],[1,2,0,4,5,3,8,6,7],[8,7,6,5,4,3,2,1,0]][n%3],foto:ESP.quadro&&ESP.quadro.tipo==='foto'?{fileId:ESP.quadro.fileId,legenda:ESP.quadro.legenda,imagem:ESP.quadro.imagem}:null};ESP.jog[p.jogo].push(x);}
  const t=x.jogo==='forca'?{id:x.id,jogo:'forca',situacao:x.situacao,n:x.n,dica:x.palavra[1],codigo:x.palavra[0].split('').reverse().map(c=>c.charCodeAt(0)+7),erros:6}:{id:x.id,jogo:'quebra',situacao:x.situacao,n:x.n,ordem:x.ordem,foto:x.foto};
  return {partida:t,estado:jogEstado()};}
if(nome==='terminarJogoCPT'){const x=ESP.jog.forca.concat(ESP.jog.quebra).find(y=>y.id===p.partida);if(!x||x.situacao!=='jogando')throw new Error('Essa partida já terminou.');let venceu;
  if(x.jogo==='forca'){const nm=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase(),alvo=new Set(nm(x.palavra[0]).replace(/[^A-Z]/g,'')),vis=new Set();let err=0;venceu=false;for(const l of p.letras){vis.add(l);if(!alvo.has(l))err++;if(err>=6)break;if([...alvo].every(a=>vis.has(a))){venceu=true;break;}}}
  else{const o=x.ordem.slice();p.trocas.forEach(([a,b])=>{[o[a],o[b]]=[o[b],o[a]];});venceu=o.every((v,i)=>v===i);}
  const ja=ESP.jog[x.jogo].some(y=>y.pontos>0);x.situacao=venceu?'venceu':'perdeu';x.pontos=venceu&&!ja?5:0;
  return {resultado:venceu?(x.pontos?'Venceu! +5 pontos':'Venceu!'):x.jogo==='forca'?'Não foi dessa vez: a palavra era '+x.palavra[0]+'.':'Partida encerrada.',situacao:x.situacao,pontosGanhos:x.pontos,palavra:x.jogo==='forca'?x.palavra[0]:undefined,estado:jogEstado(),pontos:espPontos()};}
if(nome==='responderQuizCPT'){if(!ESPdono)throw new Error('O quiz está reservado à administração técnica durante o período de testes.');const q=p.tipo==='dia'?QD:QS[ESP.quiz.semana.length];if(!q)throw new Error('Você já fez o quiz desta semana. Na segunda tem outro!');if(p.tipo==='dia'&&ESP.quiz.dia)throw new Error('Você já respondeu a pergunta de hoje. Volte amanhã!');
  if(p.id!==q.id)throw new Error('A pergunta mudou. Atualize a página.');const r={id:q.id,escolha:p.escolha,acertou:p.escolha===q.certa};if(p.tipo==='dia')ESP.quiz.dia=r;else ESP.quiz.semana.push(r);
  return {resultado:r.acertou?'Acertou! +'+(p.tipo==='dia'?2:10)+' pontos':'Quase! Veja a explicação.',resposta:resS(r),estado:quizEstado(),pontos:espPontos()};}
const espDias=()=>Object.values(ESP.notas).filter(n=>n.texto.trim().length>=20).length;
const espPend=()=>{if(!ESP.perfil)return [];const r=ESP.perfil.resgates,out=[];if(!r['semana:atual'])out.push({chave:'semana:atual',tipo:'semana',titulo:'Presente da semana',texto:'Escolha um mascote novo ou uma peça.'});for(let i=1;i<=Math.floor(espDias()/5);i++)if(!r['caderno:'+i*5])out.push({chave:'caderno:'+i*5,tipo:'caderno',titulo:i*5+' dias de caderno',texto:'Escolha uma peça nova.'});return out;};
if(nome==='carregarMeuEspacoCPT'){const dia=(p&&p.data)||hojeE,n=ESP.notas[dia],l=ESP.listas[dia];return {hoje:hojeE,data:dia,perfil:ESP.perfil,novoElenco:ESPdono,kit:ESPdono?Object.values(CAT.kit):[],classicos:ESPdono?CAT.classicos:{},precoClassico:CAT.precoClassico,catalogo:CAT.catalogo.filter(x=>ESPdono||!CAT.pecasNovas.includes(x.id)),especies:ESPdono?CAT.especiesNovas:CAT.especies,cores:CAT.cores,slots:CAT.slots,coresEspeciais:ESPdono?CAT.coresEspeciais:{},precoCor:CAT.precoCor,pontos:espPontos(),pendentes:espPend(),nota:n?{data:dia,...n}:{data:dia,texto:'',versao:0},lista:l?{data:dia,...l}:{data:dia,itens:[],versao:0},
  caderno:{dias:espDias(),porPeca:5,minimo:20,recentes:Object.entries(ESP.notas).filter(([,n])=>n.texto.trim()).map(([d,n])=>({data:d,trecho:n.texto.slice(0,90)}))},proximos:[],regras:{pontosPorTarefa:10,tarefasPorDia:8},trabalho:{recados:naoLidos().length,lembretes:lemPendentes()},recados:{novos:naoLidos().slice(0,3).map(pubRec),total:naoLidos().length},lembretes:lemDia(dia),pessoas:pessoasCom.map(({email,nome})=>({email,nome})),quadro:ESP.quadro||{tipo:'paisagem',paisagem:'santo-andre'},paisagens:{'santo-andre':'Santo André',rio:'Beira do rio','por-do-sol':'Pôr do sol',noite:'Noite estrelada'},saber:saberE(),jogos:ESPdono?jogEstado():undefined,placar:ESPdono?(()=>{const seg=n=>{const d=new Date(hojeE+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7-7*n);return d.toISOString().slice(0,10);},extra=espPontos().ganhos;return {semana:'atual',inicio:seg(0),pontos:268+extra,tarefas:21,acertos:17,vitorias:4,meta:400,atingiu:268+extra>=400,historico:[[3,312],[2,455],[1,388],[0,268+extra]].map(([n,pt])=>({semana:'S'+n,inicio:seg(n),pontos:pt,atual:n===0}))};})():undefined};}
if(nome==='salvarMascoteCPT'){let pf=ESP.perfil?JSON.parse(JSON.stringify(ESP.perfil)):null,res='';if(p.acao==='iniciar'){if(!p.nome)throw new Error('Preencha: nome do mascote.');pf={mascotes:[{especie:p.especie,nome:p.nome,equipado:ESPdono?{...CAT.kit}:{},cor:p.cor||''}],ativo:0,pecas:[],resgates:{},compras:[],versao:0};res='Bem-vindo(a), '+p.nome+'!';}else{const m=pf.mascotes[pf.ativo];
  if(p.acao==='nomear'){m.nome=p.nome;res='Agora seu mascote se chama '+p.nome+'.';}
  if(p.acao==='colorir'){if(p.cor&&!CAT.cores[p.cor]&&!(CAT.coresEspeciais[p.cor]&&(pf.cores||[]).includes(p.cor)))throw new Error('Essa cor especial ainda não é sua. Ela fica na loja de cores.');m.cor=p.cor||'';res=m.cor?m.nome+' agora está '+(CAT.cores[m.cor]||CAT.coresEspeciais[m.cor]).toLowerCase()+'.':m.nome+' voltou à cor original.';}
  if(p.acao==='comprarCor'){if(!ESPdono)throw new Error('As cores especiais chegam junto com o elenco novo.');pf.cores=pf.cores||[];if(pf.cores.includes(p.cor))throw new Error('Você já tem essa cor.');if(espPontos().saldo<CAT.precoCor)throw new Error('Faltam pontos: complete tarefas do seu checklist ou responda o quiz.');pf.cores.push(p.cor);pf.compras.push({item:'cor:'+p.cor,preco:CAT.precoCor});m.cor=p.cor;res='Cor especial: '+m.nome+' agora está '+CAT.coresEspeciais[p.cor].toLowerCase()+'!';}
  if(p.acao==='quadro'){if(p.tipo==='foto'){if(/08$/.test(p.fileId))throw new Error('Essa foto não abriu. Escolha outra da Galeria.');ESP.quadro={tipo:'foto',fileId:p.fileId,legenda:p.legenda||'',imagem:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="220" height="165"><rect width="220" height="165" fill="#8fbf9f"/><circle cx="60" cy="50" r="22" fill="#fff8"/><path d="M0 165 L70 90 L120 140 L165 100 L220 165Z" fill="#0003"/></svg>')};res='Foto nova no quadro!';}else{ESP.quadro={tipo:'paisagem',paisagem:p.paisagem};res='Quadro trocado.';}}
  if(p.acao==='ativar'){pf.ativo=p.indice;res=pf.mascotes[p.indice].nome+' está com você agora.';}
  if(p.acao==='vestir'){if(p.item)m.equipado[p.slot]=p.item;else delete m.equipado[p.slot];res='Pronto!';}
  if(p.acao==='resgatar'){if(pf.resgates[p.chave])throw new Error('Esse presente já foi resgatado.');if(p.escolha==='mascote'){pf.mascotes.push({especie:p.especie,nome:p.nome,equipado:ESPdono?{...CAT.kit}:{}});pf.ativo=pf.mascotes.length-1;res='Chegou '+p.nome+'!';}else{const it=CAT.catalogo.find(x=>x.id===p.item);pf.pecas.push(it.id);m.equipado[it.slot]=it.id;res='Peça nova: '+it.nome+'!';}pf.resgates[p.chave]={em:new Date().toISOString()};}
  if(p.acao==='comprarClassico'){if(espPontos().saldo<CAT.precoClassico)throw new Error('Faltam pontos: complete tarefas do seu checklist.');pf.mascotes.push({especie:p.especie,nome:p.nome,equipado:{...CAT.kit},cor:''});pf.ativo=pf.mascotes.length-1;pf.compras.push({item:'mascote:'+p.especie,preco:CAT.precoClassico});res='Clássico de volta: '+p.nome+'!';}
  if(p.acao==='comprar'){const it=CAT.catalogo.find(x=>x.id===p.item);if(espPontos().saldo<it.preco)throw new Error('Faltam pontos: complete tarefas do seu checklist.');pf.pecas.push(it.id);pf.compras.push({item:it.id,preco:it.preco});m.equipado[it.slot]=it.id;res='Peça exclusiva: '+it.nome+'!';}}
  pf.versao=(pf.versao||0)+1;ESP.perfil=pf;return {resultado:res,perfil:pf,pontos:espPontos(),pendentes:espPend()};}
if(nome==='salvarNotaCPT'){const antes=espDias();ESP.notas[p.data]={texto:p.texto,versao:((ESP.notas[p.data]||{}).versao||0)+1};const dias=espDias();return {resultado:Math.floor(dias/5)>Math.floor(antes/5)?'Caderno salvo. Você completou '+dias+' dias: tem peça nova esperando!':'Salvo.',nota:{data:p.data,...ESP.notas[p.data]},dias,pendentes:espPend()};}
if(nome==='salvarChecklistCPT'){const ant=new Map(((ESP.listas[p.data]||{}).itens||[]).map(t=>[t.id,t]));let pts=[...ant.values()].filter(t=>t.pontuado).length,novos=0;const itens=p.itens.map(t=>{const v=ant.get(t.id),x={...t,pontuado:!!(v&&v.pontuado)};if(t.feito&&!x.pontuado&&p.data<=hojeE&&pts<8){x.pontuado=true;pts++;novos++;}return x;});
  let comLem=false;itens.filter(x=>x.lembrete).forEach(x=>{comLem=true;const l=COM.lembretes.find(y=>y.id===x.lembrete);if(!l||!lemPara(l))throw new Error('Essa tarefa não é para você.');if((l.situacao==='feito')!==!!x.feito){l.situacao=x.feito?'feito':'pendente';l.feitoPor=x.feito?perfilDemo.email:'';}});
  ESP.listas[p.data]={itens,versao:((ESP.listas[p.data]||{}).versao||0)+1};return {resultado:novos?'+'+novos*10+' pontos!':'Checklist salvo.',lista:{data:p.data,...ESP.listas[p.data]},pontos:espPontos(),lembretes:comLem?lemDia(p.data):undefined};}
// 2.33: Levantamento de traçado. window.CPT_PREVIA.semRede=true simula o celular sem internet.
if(nome==='listarLevantamentoCPT'||nome==='enviarLevantamentoCPT'){if(window.CPT_PREVIA.semRede)throw new Error('Sem conexão com o servidor.');
  const LV=window.CPT_LEV=window.CPT_LEV||{itens:[{id:'LEV-1',obraId:'OBR-0117',obra:'Viela Carijós',bairro:'Vila Linda',rua:'Rua das Flores',numero:'10',tipo:'Residencial',imovel:'Casa',resultado:'Comunicado',observacao:'',visitadaEm:'2026-10-05T13:00:00Z',nome:'Equipe social de exemplo',atualizadoEm:''},
    {id:'LEV-2',obraId:'OBR-0117',obra:'Viela Carijós',bairro:'Vila Linda',rua:'Rua das Flores',numero:'12',tipo:'Comercial',imovel:'Casa',resultado:'Contato com morador',observacao:'Padaria',visitadaEm:'2026-10-05T13:10:00Z',nome:'Equipe social de exemplo',atualizadoEm:''}],ops:{}};
  const nm=v=>String(v==null?'':v).normalize('NFD').replace(/[̀-ͯ]/g,'').trim().toLowerCase().replace(/\s+/g,' '),ch=(o,r,n)=>[o,nm(r),nm(n).replace(/\s+/g,'')].join('|');
  const obrasL=obrasDemo.map(o=>({id:o.id,nome:o.exibir||o.nomeUso||o.nome,oficial:o.nome,apelidos:o.apelidos||[],bairros:o.bairros,situacao:o.situacao}));
  if(nome==='listarLevantamentoCPT')return {itens:LV.itens.slice(),obras:obrasL,tipos:['Residencial','Comercial','Outro'],imoveis:['Casa','Prédio','Terreno'],resultados:['Comunicado','Contato com morador'],agora:new Date().toISOString()};
  const res=p.itens.map(x=>{if(LV.ops[x.operacaoId])return {operacaoId:x.operacaoId,situacao:'ja-recebida',casa:LV.ops[x.operacaoId]};const o=obrasL.find(y=>y.id===x.obraId);if(!o)return {operacaoId:x.operacaoId,situacao:'invalida',mensagem:'Obra não encontrada no catálogo.'};
    const e=LV.itens.find(c=>ch(c.obraId,c.rua,c.numero)===ch(x.obraId,x.rua,x.numero));if(e&&!x.atualizar)return {operacaoId:x.operacaoId,situacao:'duplicada',casa:e};
    const c={id:e?e.id:'LEV-'+crypto.randomUUID(),obraId:o.id,obra:o.nome,bairro:x.bairro,rua:x.rua,numero:x.numero,tipo:x.tipo,imovel:x.imovel,resultado:x.resultado,observacao:x.observacao||'',visitadaEm:x.visitadaEm,nome:perfilDemo.nome,atualizadoEm:e?new Date().toISOString():''};
    if(e)Object.assign(e,c);else LV.itens.push(c);LV.ops[x.operacaoId]=e||c;return {operacaoId:x.operacaoId,situacao:e?'atualizada':'salva',casa:e||c};});
  const n=t=>res.filter(r=>r.situacao===t).length;return {resultados:res,salvas:n('salva')+n('atualizada')+n('ja-recebida'),duplicadas:n('duplicada'),invalidas:n('invalida')};}
if(nome==='listarEquipeCPT')return {pessoas:equipeDemo,agendaUrl:'https://docs.google.com/spreadsheets/'};
if(nome==='salvarPessoaCPT'){const i=equipeDemo.findIndex(x=>x.email===p.email);if(i>=0)equipeDemo[i]=p;else equipeDemo.push(p);return {resultado:'Cadastro demonstrativo atualizado.'};}
if(nome==='conferirSaudeCPT')return {itens:[{nome:'Registros',quantidade:54,unidade:'registros',orientacao:'Dados fictícios desta prévia.'}],tempoServidorMs:120};
throw new Error('Operação indisponível na prévia.');}};
</script>'''
s=(root/'src/Aplicacao.html').read_text().replace("<?!= incluirCPT_('Estilos'); ?>",'<meta name="viewport" content="width=device-width, initial-scale=1"><title>CPT · Prévia demonstrativa</title>'+ (root/'src/Estilos.html').read_text()).replace("<?!= incluirCPT_('Interacoes'); ?>",mock+(root/'src/Interacoes.html').read_text())
s=s.replace("<?!= incluirCPT_('Agenda'); ?>",(root/'src/Agenda.html').read_text())
# ?inicial=1 simula o perfil já embutido pelo doGet (como na implantação real).
s=s.replace("<script>window.CPT_INICIAL=<?!= inicial ?>;</script>","<script>if(new URLSearchParams(location.search).get('inicial'))window.CPT_INICIAL={perfil:{email:'victor@example.com',nome:'Victor Xavier',ativo:true,papeis:['administrador','administrativo','gestao','atendimento','socioambiental','comunicacao','comercializacao']},conta:'victor@example.com',mes:'2026-09',versao:'2.2.0'};</script>")
s=s.replace("<?!= incluirCPT_('Inicio'); ?>",(root/'src/Inicio.html').read_text())
s=s.replace("<?!= incluirCPT_('Atendimentos'); ?>",(root/'src/Atendimentos.html').read_text())
s=s.replace("<?!= incluirCPT_('Obras'); ?>",(root/'src/Obras.html').read_text())
s=s.replace("<?!= incluirCPT_('Mapa'); ?>",(root/'src/Mapa.html').read_text())
s=s.replace("<?!= incluirCPT_('Gestao'); ?>",(root/'src/Gestao.html').read_text())
s=s.replace("<?!= incluirCPT_('Comunicacao'); ?>",(root/'src/Comunicacao.html').read_text())
s=s.replace("<?!= incluirCPT_('Recados'); ?>",(root/'src/Recados.html').read_text())
s=s.replace("<?!= incluirCPT_('MeuEspaco'); ?>",(root/'src/MeuEspaco.html').read_text())
s=s.replace("<?!= incluirCPT_('Mascotes'); ?>",(root/'src/Mascotes.html').read_text())
s=s.replace("<?!= incluirCPT_('Saber'); ?>",(root/'src/Saber.html').read_text())
s=s.replace("<?!= incluirCPT_('Jogos'); ?>",(root/'src/Jogos.html').read_text())
s=s.replace("<?!= incluirCPT_('Placar'); ?>",(root/'src/Placar.html').read_text())
s=s.replace("<?!= incluirCPT_('Visual'); ?>",(root/'src/Visual.html').read_text())
s=s.replace("<?!= incluirCPT_('Organograma'); ?>",(root/'src/Organograma.html').read_text())
s=s.replace("<?!= incluirCPT_('Levantamento'); ?>",(root/'src/Levantamento.html').read_text())
s=s.replace("<?!= incluirCPT_('Relatos'); ?>",(root/'src/Relatos.html').read_text())
s=s.replace("<?!= incluirCPT_('Graficos'); ?>",(root/'src/Graficos.html').read_text())
import subprocess,json
cat=subprocess.run(['node','-e',"const fs=require('fs'),vm=require('vm'),c={};vm.createContext(c);vm.runInContext(fs.readFileSync(process.argv[1],'utf8')+';this.x={catalogo:PessoalCPT.catalogo,especies:PessoalCPT.especiesAntigas,especiesNovas:PessoalCPT.especiesNovas,classicos:PessoalCPT.classicos,precoClassico:PessoalCPT.precoClassico,kit:PessoalCPT.kit,cores:PessoalCPT.cores,slots:PessoalCPT.slots,pecasNovas:PessoalCPT.pecasNovas,coresEspeciais:PessoalCPT.coresEspeciais,precoCor:PessoalCPT.precoCor};',c);console.log(JSON.stringify(c.x))",str(root/'src/PessoalCPT.gs')],capture_output=True,text=True,check=True).stdout.strip()
s=s.replace('__CATALOGO__',cat)
cont=subprocess.run(['node','-e',"const fs=require('fs'),vm=require('vm'),c={};vm.createContext(c);vm.runInContext(fs.readFileSync(process.argv[1],'utf8')+';this.x={fontes:ConteudoSaneamentoCPT.fontes,temas:ConteudoSaneamentoCPT.temas,eixos:ConteudoSaneamentoCPT.eixos,correcoes:ConteudoSaneamentoCPT.correcoes,curiosidades:ConteudoSaneamentoCPT.curiosidades,perguntas:ConteudoSaneamentoCPT.perguntas,campanhas:ConteudoSaneamentoCPT.campanhas,datas:ConteudoSaneamentoCPT.datas};',c);console.log(JSON.stringify(c.x))",str(root/'src/ConteudoSaneamentoCPT.gs')],capture_output=True,text=True,check=True).stdout.strip()
s=s.replace('__CONTEUDO__',cont)
jog=subprocess.run(['node','-e',"const fs=require('fs'),vm=require('vm'),c={};vm.createContext(c);vm.runInContext(fs.readFileSync(process.argv[1],'utf8')+';this.x={palavras:JogosCPT.palavras};',c);console.log(JSON.stringify(c.x))",str(root/'src/JogosCPT.gs')],capture_output=True,text=True,check=True).stdout.strip()
s=s.replace('__JOGOS__',jog)
(root/'previa/CPT_Previa_1_2_1.html').write_text(s)
