from pathlib import Path
root=Path(__file__).resolve().parents[1]
mock=r'''<script>
const perfilDemo={email:'victor@example.com',nome:'Victor Xavier',ativo:true,papeis:['administrador','administrativo','gestao','atendimento','socioambiental','comunicacao','comercializacao']};
let obsDemo=[];let obrasDemo=[{id:'OBR-0117',nome:'Viela Sanitária x Carijós – Obra Córrego',bairros:['Jardim do Estádio','Vila Linda'],noFormulario:true,noFormularioAgora:true,situacao:'Em andamento',inicioObra:'2026-08-19',inicioComunicacao:'2026-08-19',termino:'',publico:'C',impacto:'Alto',observacao:'Ampliação da rede de esgoto.',atualizadoEm:new Date(Date.now()-864e5).toISOString(),logradouroPAC16:'Viela Sanitária',metodoPAC16:'Vala',tipo:'Rede coletora',endereco:'',latitude:null,longitude:null},{id:'OBR-0074',nome:'Córrego Apiaí – Margem Esquerda Orquídea',bairros:['Vila Linda'],noFormulario:true,noFormularioAgora:true,situacao:'Paralisada',inicioObra:'2026-07-16',inicioComunicacao:'2026-07-16',termino:'',publico:'A, B',impacto:'Médio',observacao:'',atualizadoEm:new Date(Date.now()-12*864e5).toISOString(),logradouroPAC16:'',metodoPAC16:'',tipo:'',endereco:'Rua das Orquídeas',latitude:null,longitude:null}];
const equipeDemo=[perfilDemo,{email:'paula@example.com',nome:'Comunicadora de exemplo',ativo:true,papeis:['comunicacao']},{email:'social@example.com',nome:'Equipe social de exemplo',ativo:true,papeis:['socioambiental']}];
let entregaDemo=null;
let eventosDemo=[{id:'AG-demo1',versao:1,titulo:'Sensibilização com moradores',data:'2026-09-30',inicio:'09:00',fim:'10:30',frentes:['socioambiental','comunicacao'],responsaveis:['social@example.com','paula@example.com'],natureza:'externo',status:'confirmada',descricao:'Atividade fictícia para explorar a interface.',obra:'Frente demonstrativa',bairro:'Vila Linda',alteradoPor:'victor@example.com',podeEditar:true},{id:'AG-demo2',versao:1,titulo:'Conferência das entregas do mês',data:'2026-09-30',inicio:'14:00',fim:'15:00',frentes:['administrativo'],responsaveis:['victor@example.com'],natureza:'interno',status:'planejada',descricao:'Exemplo de planejamento interno.',obra:'',bairro:'',alteradoPor:'victor@example.com',podeEditar:true}];
window.CPT_PREVIA={chamadas:[],chamar:async function(nome,p){const lat=Number(new URLSearchParams(location.search).get('latencia')||180),t0=performance.now();await new Promise(r=>setTimeout(r,lat));window.CPT_PREVIA.chamadas.push({nome,inicio:Math.round(t0),fim:Math.round(performance.now()+0)});
const registros=Array.from({length:36},(_,i)=>({id:'REG-'+String(i).padStart(24,'0'),procedimento:i%3?'Relato de atividade':'Pesquisa de Satisfação',data:'2026-09-'+String(28-i%22).padStart(2,'0'),atividade:['Diálogo com moradores','Sensibilização em frente de obra','Água, cuidado e território'][i%3],bairro:['Vila Linda','Jardim do Estádio','Vila Assunção'][i%3],responsavel:'Equipe de exemplo',obra:'Frente de obra demonstrativa',origem:'Dados fictícios',conferencia:''}));
const casos=Array.from({length:7},(_,i)=>({protocolo:'DEMO-'+(100+i),nome:'Pessoa de exemplo '+(i+1),assunto:['Orientação sobre a obra','Solicitação de vistoria','Recomposição da calçada'][i%3],endereco:'Endereço fictício · Santo André',area:'Atendimento',status:i<2?'Concluído':'Em acompanhamento',concluido:i<2,abertura:'2026-09-12',conclusao:i<2?'2026-09-28':'',responsavel:'Equipe de exemplo',obra:'Frente demonstrativa',origem:'Demonstração',proximaAcao:'Conferir o retorno da equipe responsável.',atualizacao:'Informação fictícia para demonstrar a interface.'}));
if(nome==='carregarPerfilCPT'){const forced=new URLSearchParams(location.search).get('perfil');if(forced==='negado')throw new Error('Sua conta (alguem@veolia.com) ainda não está cadastrada ou está inativa. Peça à administração técnica para liberar seu acesso em Equipe e acessos.');return {conta:perfilDemo.email,perfil:forced?{...perfilDemo,nome:'Paula',papeis:[forced]}:perfilDemo,versao:'2.0.0'};}
if(nome==='listarObservacoesCPT')return {protocolo:p.protocolo,itens:obsDemo.filter(x=>x.protocolo===p.protocolo).slice().reverse()};
if(nome==='adicionarObservacaoCPT'){const o={id:'OBS-'+crypto.randomUUID(),protocolo:p.protocolo,consultado:p.protocolo,em:new Date().toISOString(),autor:perfilDemo.email,nome:perfilDemo.nome,canal:p.canal,texto:p.texto};obsDemo.push(o);return {resultado:'Observação registrada no caso '+p.protocolo+'.',observacao:o};}
if(nome==='conferirMeuAcessoCPT')return {etapas:[{nome:'Conta Google',ok:true,mensagem:'alguem@veolia.com'},{nome:'Cadastro na aplicação',ok:false,mensagem:'Conta não cadastrada.'}]};
if(nome==='listarObrasCPT')return {obras:obrasDemo,bairros:['Jardim do Estádio','Vila Assunção','Vila Linda'],situacoes:['Em andamento','Paralisada','Finalizada','A confirmar'],impactos:['Alto','Médio','Baixo'],podeEditar:!new URLSearchParams(location.search).get('perfil'),formulario:{situacao:'ok',texto:'Salvo! 12 obras + 2 opções especiais.'}};
if(nome==='salvarObraCPT'){const o={...(obrasDemo.find(x=>x.id===p.id)||{}),...p,id:p.id||'OBR-0'+(200+obrasDemo.length),atualizadoEm:new Date().toISOString(),noFormularioAgora:p.noFormulario};obrasDemo=obrasDemo.filter(x=>x.id!==o.id).concat([o]);return {resultado:'Obra salva apenas nesta prévia.',obra:o};}
if(nome==='confirmarObraCPT'){const o=obrasDemo.find(x=>x.id===p.id);o.atualizadoEm=new Date().toISOString();return {resultado:'Situação confirmada hoje.',obra:o};}
if(nome==='conferirFechamentoCPT')return {mes:p,numeros:{atividades:38,participantes:412,frentes:7,relatos:31,relatosProntos:22,satisfacao:44,casosAbertos:5,casosConcluidos:3,agendaProximoMes:6},satisfacao:{total:44,meta:60,semanas:[{de:p+'-01',ate:p+'-07',parcial:false,total:15,meta:15},{de:p+'-08',ate:p+'-14',parcial:false,total:12,meta:15},{de:p+'-15',ate:p+'-21',parcial:false,total:10,meta:15},{de:p+'-22',ate:p+'-28',parcial:false,total:7,meta:15},{de:p+'-29',ate:p+'-30',parcial:true,total:0,meta:15}]},verificacoes:[{nome:'Relatos preparados para o relatório',situacao:'atencao',detalhe:'22 de 31 prontos, 4 em rascunho.',acao:{route:'registros',procedimento:'Relato de atividade'}},{nome:'Público informado nos relatos',situacao:'pendente',detalhe:'3 relatos sem número de participantes.',acao:{route:'registros',pendencia:'publico'}},{nome:'Pesquisas de satisfação (meta 60 no mês)',situacao:'atencao',detalhe:'44 de 60.',acao:null},{nome:'Cronograma do mês seguinte',situacao:'ok',detalhe:'6 atividades previstas.',acao:{route:'cronograma'}}],historico:[]};
if(nome==='gerarBaseRelatorioCPT'){await new Promise(r=>setTimeout(r,600));return {resultado:'Base do relatório gerada (versão 1) — prévia, nenhum arquivo criado.',documento:'https://docs.google.com/document/',planilha:'https://docs.google.com/spreadsheets/',versao:1,avisos:[]};}
if(nome==='carregarInicioCPT')return {perfil:perfilDemo,comparacao:{anterior:42,mesAnterior:'2026-08'},satisfacao:{mes:44,meta:60,semana:null},conta:'Prévia demonstrativa',atualizadoEm:new Date().toISOString(),mes:(p&&p.mes)||p,indicadores:{registros:54,participacoes:249,acoes:38,pessoas:412,frentes:7,diagnosticos:2,bairros:5,abertos:5,concluidos:2,recebidasNoMes:4,concluidosNoMes:3,relatosSemPublico:3,frase:'Foram contabilizadas 38 ações socioambientais, totalizando 412 pessoas alcançadas.'},destinos:[{item:'2',titulo:'Diagnóstico das áreas de trabalho',tipo:'diagnostico',quantidade:2,prontos:1},{item:'4.1',titulo:'Reuniões, grupos de discussão e fóruns periódicos',tipo:'relato',quantidade:1,prontos:1},{item:'4.2',titulo:'Ações sob eixo de gestão de resíduos sólidos',tipo:'relato',quantidade:2,prontos:0},{item:'4.3',titulo:'Ações preventivas às doenças de veiculação hídrica',tipo:'relato',quantidade:0,prontos:0},{item:'4.4',titulo:'Ações de Educação Socioambiental',tipo:'relato',quantidade:1,prontos:0},{item:'4.5',titulo:'Governança Colaborativa',tipo:'relato',quantidade:0,prontos:0},{item:'7',titulo:'Atividades da Unidade Móvel Socioambiental (UMS)',tipo:'relato',quantidade:3,prontos:1},{item:'9',titulo:'Atividades Complementares (DDS, treinamentos e campanhas internas)',tipo:'relato',quantidade:4,prontos:2},{item:'3',titulo:'Atividades desenvolvidas no período (tabela e fotos por frente)',tipo:'consolidado',quantidade:27,prontos:0}],procedimentos:[{nome:'Relato de atividade',quantidade:31},{nome:'Pesquisa de Satisfação',quantidade:12},{nome:'Acompanhamento de Vistoria Cautelar',quantidade:7},{nome:'Diagnóstico de Área',quantidade:4}],dias:[2,3,4,7,8,9,10,11,14,15,16,17,18,21,22,23,24,25,28].map((v,i)=>({data:'2026-09-'+String(v).padStart(2,'0'),quantidade:i===0?1:[2,4,3,1,5][i%5]})),recentes:registros.slice(0,5),filtros:{obras:['Frente de obra demonstrativa'],procedimentos:['Relato de atividade','Pesquisa de Satisfação'],bairros:['Vila Linda','Jardim do Estádio','Vila Assunção']},links:{}};
if(nome==='buscarRegistrosCPT'){const rows=registros.filter(r=>(!p.busca||JSON.stringify(r).toLowerCase().includes(p.busca.toLowerCase()))&&(!p.procedimento||r.procedimento===p.procedimento)&&(!p.bairro||r.bairro===p.bairro)&&p.mes==='2026-09');const start=Number(p.cursor||0);return {itens:rows.slice(start,start+24),proximoCursor:start+24<rows.length?String(start+24):null};}
if(nome==='abrirRegistroCPT')return {registro:registros.find(r=>r.id===p),anexos:[],campos:[{titulo:'Como foi a atividade?',valor:'A equipe conversou com os moradores sobre o andamento da obra e registrou as dúvidas para acompanhamento. Este texto é apenas demonstrativo.'},{titulo:'Participantes informados',valor:18}]};
if(nome==='buscarAtendimentosCPT'){const rows=casos.filter(r=>(!p.estado||(p.estado==='concluidos')===r.concluido)&&(!p.busca||JSON.stringify(r).toLowerCase().includes(p.busca.toLowerCase())));return {itens:rows,total:rows.length,proximaPagina:null};}
if(nome==='abrirAtendimentoCPT'){const papel=new URLSearchParams(location.search).get('perfil'),conduz=!papel||['atendimento','gestao','administrativo'].includes(papel),exec=conduz||papel==='gestao';window.CPT_ESTADO=window.CPT_ESTADO||{};const st=window.CPT_ESTADO[p]||{};const f={...casos.find(r=>r.protocolo===p),...st.ficha};
  return {ficha:f,protocoloConsultado:p,procedencia:st.procedencia||'Em análise',versao:st.versao||'v1',abertura:{tipo:'Reclamação',canal:'Atendimento itinerante',urgencia:'Média',solicitacao:'Relato fictício: saída de lama na calçada após a obra.',telefone:exec?'(11) 0000-0000':'',contatoOculto:!exec,registroId:''},opcoes:{status:['Recebida','Em andamento','Concluída'],procedencias:['Em análise','Procedente','Não procedente'],areas:['Atendimento','Execução','Socioambiental','Comunicação','Gestão']},pode:{atualizar:conduz,executar:conduz,finalizar:conduz,reabrir:conduz,corrigir:conduz,incorporar:conduz,fichaOficial:conduz},correcao:conduz?{nome:f.nome,telefone:'(11) 0000-0000',email:'',endereco:f.endereco,assunto:f.assunto,tipo:'Reclamação',canal:'Atendimento itinerante',local:'',solicitacao:'Relato fictício: saída de lama na calçada após a obra.'}:null,fichaAtualizada:!!st.fichaOk};}
if(nome==='gerarFichaOficialCPT'){window.CPT_ESTADO=window.CPT_ESTADO||{};const st=window.CPT_ESTADO[p.protocolo]||(window.CPT_ESTADO[p.protocolo]={ficha:{},eventos:[]});st.fichaOk=true;st.ficha.pdf='https://drive.google.com/file/d/previa/view';st.eventos.unshift({tipo:'Ficha oficial gerada',data:'agora',status:'',autor:'Prévia',resumo:'Documento e PDF no modelo oficial'});return {gerada:true,documento:'https://docs.google.com/document/d/previa/edit',pdf:st.ficha.pdf,resultado:'Ficha oficial gerada.'};}
if(['atualizarAtendimentoCPT','registrarExecucaoCPT','finalizarAtendimentoCPT','reabrirAtendimentoCPT','corrigirAtendimentoCPT','incorporarAtendimentoCPT'].includes(nome)){window.CPT_ESTADO=window.CPT_ESTADO||{};const st=window.CPT_ESTADO[p.protocolo]||(window.CPT_ESTADO[p.protocolo]={ficha:{},eventos:[]});const v='v'+(Number(String(st.versao||'v1').slice(1))+1);
  const muda={atualizarAtendimentoCPT:{status:p.status,area:p.area,proximaAcao:p.proximaAcao},registrarExecucaoCPT:{status:'Em andamento',proximaAcao:'Conferir execução e finalizar ficha'},finalizarAtendimentoCPT:{status:'Concluída',concluido:true,conclusao:p.data},reabrirAtendimentoCPT:{status:'Em andamento',concluido:false,conclusao:'',proximaAcao:p.proximaAcao},corrigirAtendimentoCPT:{nome:p.dados&&p.dados.nome},incorporarAtendimentoCPT:{}}[nome];
  Object.assign(st.ficha,muda);st.versao=v;if(p.procedencia)st.procedencia=p.procedencia;st.eventos.unshift({tipo:{atualizarAtendimentoCPT:'Atualização',registrarExecucaoCPT:'Execução',finalizarAtendimentoCPT:'Finalização',reabrirAtendimentoCPT:'Reabertura',corrigirAtendimentoCPT:'Correção de ficha',incorporarAtendimentoCPT:'Vínculo de protocolos'}[nome],data:'agora',status:muda.status,autor:'Prévia',resumo:p.feito||p.conclusao||p.motivo||p.proximaAcao||''});
  return {resultado:'Registrado apenas nesta prévia.',versao:v};}
if(nome==='carregarCronogramaCPT')return {itens:eventosDemo.filter(e=>e.data.startsWith(p.mes)),pessoas:equipeDemo,perfil:perfilDemo};
if(nome==='salvarAtividadeCPT'){const e={...p,id:p.id||'AG-'+crypto.randomUUID(),versao:Number(p.versao||0)+1,podeEditar:true,alteradoPor:perfilDemo.email};eventosDemo=eventosDemo.filter(x=>x.id!==e.id).concat([e]);return {resultado:'Salvo apenas nesta prévia. Nenhuma planilha foi alterada.',evento:e};}
if(nome==='historicoAtividadeCPT')return {versoes:eventosDemo.filter(e=>e.id===p)};
if(nome==='consultarHistoricoFichaCPT')return {itens:[...(((window.CPT_ESTADO||{})[p.protocolo]||{}).eventos||[]),{id:'MOV-demo',protocolo:p.protocolo,data:'30/09/2026 09:00',tipo:'Atualização demonstrativa',status:'Em acompanhamento',autor:'Equipe de exemplo',resumo:'Contato com o morador registrado. Dado fictício.'}],proximoCursor:null};
if(nome==='carregarMesaSocioambientalCPT'){const it=(n,item,ativ,sit)=>({id:registros[n].id,data:registros[n].data,atividade:ativ,titulo:sit==='sem'?'':ativ+' (revisado)',bairro:registros[n].bairro,frente:'Frente demonstrativa',publico:12+n,responsavel:'Equipe de exemplo',sugerido:item,destino:item,situacao:(window.CPT_SITUACAO||{})[registros[n].id]||sit,versao:sit==='sem'?0:1,documento:sit==='pronto'?'https://drive.google.com/file/d/previa/view':''});
  const grupos=[['2','Diagnóstico das áreas de trabalho','diagnostico',[{...it(4,'2','Diagnóstico de Área','sem'),id:'REG-DIAG00000000000000000001',atividade:'Diagnóstico de Área'}]],['4.1','Reuniões, grupos de discussão e fóruns periódicos','relato',[it(1,'4.1','Realização de CAO','pronto')]],['4.2','Ações sob eixo de gestão de resíduos sólidos','relato',[it(2,'4.2','Ação Social Externa','rascunho')]],['4.3','Ações preventivas às doenças de veiculação hídrica','relato',[]],['4.4','Ações de Educação Socioambiental','relato',[it(5,'4.4','Ação Social Externa','sem')]],['4.5','Governança Colaborativa','relato',[]],['7','Atividades da Unidade Móvel Socioambiental (UMS)','relato',[it(7,'7','Atendimento em tenda','sem')]],['9','Atividades Complementares (DDS, treinamentos e campanhas internas)','relato',[it(8,'9','DDS','pronto')]]].map(([item,titulo,tipo,itens])=>({item,titulo,tipo,itens,prontos:itens.filter(x=>x.situacao==='pronto').length,vazio:itens.length?'':'No período de referência não foram realizadas ações específicas de '+titulo.toLowerCase()+'. As atividades permanecem previstas no planejamento e serão retomadas conforme o cronograma.'}));
  return {mes:p,totais:{acoes:38,pessoas:412,semPublico:3,frentes:7,diagnosticos:1,pesquisas:12,proprios:6,prontos:2,frase:'Foram contabilizadas 38 ações socioambientais, totalizando 412 pessoas alcançadas.'},grupos,frentes:[{frente:'Viela Sanitária x Carijós',acoes:14,pessoas:160,bairros:'Vila Linda'},{frente:'Córrego Apiaí',acoes:9,pessoas:88,bairros:'Vila Linda, Jardim do Estádio'},{frente:'Atividades sem obra específica',acoes:4,pessoas:40,bairros:'Vila Assunção',semObra:true}],consolidados:27};}
if(nome==='gerarAnexosDoMesCPT'){await new Promise(r=>setTimeout(r,300));return {resultado:'Anexos gerados com 3 relato(s), cada um em página própria. (prévia)',doc:'https://docs.google.com/document/d/previa/edit',pdf:'https://drive.google.com/file/d/previa/view',avisos:[],relatos:3};}
if(nome==='gerarDocumentoSocioambientalCPT'){await new Promise(r=>setTimeout(r,400));const a={doc:'https://docs.google.com/document/d/previa/edit',pdf:'https://drive.google.com/file/d/previa/view',versao:(entregaDemo||{}).versao||1,em:new Date().toISOString()};window.CPT_ARQ={...(window.CPT_ARQ||{}),[p.tipo]:a};return {arquivo:a,arquivos:window.CPT_ARQ,resultado:'Documento gerado apenas nesta prévia.'};}
if(nome==='carregarEntregaRelatoCPT'){const diag=/^REG-DIAG/.test(p);const fonte=diag?{registro:{id:p,procedimento:'Diagnóstico de Área',data:'2026-09-21',bairro:'Vila Linda',obra:'Frente demonstrativa'},campos:[{titulo:'Relato do Diagnóstico',valor:'Rua estreita, comércio de bairro e escola próxima. Texto fictício.'},{titulo:'Quantidade de Imóveis Residênciais no Traçado',valor:'48'}],anexos:[{id:'FOTODEMO000000000001',titulo:'Fotos do diagnóstico'},{id:'FOTODEMO000000000002',titulo:'Fotos do diagnóstico'}]}:await window.CPT_PREVIA.chamar('abrirRegistroCPT',p);
  if(!diag)fonte.anexos=[{id:'FOTODEMO000000000011',titulo:'Fotos da atividade'},{id:'FOTODEMO000000000012',titulo:'Fotos da atividade'},{id:'FOTODEMO000000000013',titulo:'Fotos da atividade'}];
  const quadroRot=[['atividade','Atividade'],['local','Local'],['endereco','Endereço e bairro'],['dataHorario','Data e horário'],['mediacao','Mediação'],['publico','Público'],['objetivo','Objetivo']].map(([chave,rotulo])=>({chave,rotulo}));const campos=['frente','pvInicio','pvFim','metodo','extensao','endereco','perfil','pavimento','condicao','impacto','impactos','veiculos','pedestres','residencias','comercios','padrao','ipvs','liderancas','escolas','ubs','ongs','onibus','comunicacao','criticos'].map(c=>({chave:c,rotulo:c.toUpperCase()}));
  const e=entregaDemo&&entregaDemo.id===p?entregaDemo:null;
  return {tipo:diag?'diagnostico':'relato',fonte,hash:'demo-hash',entrega:e,historico:[],limite:diag?12:8,quadro:diag?[]:quadroRot,arquivos:window.CPT_ARQ||{},campos:diag?campos:[],sugestao:diag?{titulo:'Diagnóstico local: Frente demonstrativa',oficiais:{frente:'Frente demonstrativa',residencias:'48'},textoBase:'REGISTRO DE CAMPO\nRua estreita, comércio de bairro e escola próxima.'}:{destino:'4.4',quadro:{atividade:'Ação Social Externa · Tapete pedagógico',local:'CRAS',endereco:'Vila Linda',dataHorario:'20/09/2026 · 09:00 às 11:00',mediacao:'Equipe de exemplo',publico:'Crianças · 25 participantes',objetivo:'Educação ambiental lúdica.'}},
    destinos:[['4.1','Reuniões, grupos de discussão e fóruns periódicos','dd/mm/aaaa - Evento - Local'],['4.2','Ações sob eixo de gestão de resíduos sólidos','dd/mm/aaaa - Evento - Local'],['4.3','Ações preventivas às doenças de veiculação hídrica','dd/mm/aaaa - Evento - Local'],['4.4','Ações de Educação Socioambiental','dd/mm/aaaa - Evento - Local'],['4.5','Governança Colaborativa','dd/mm/aaaa - Evento - Local'],['7','Atividades da Unidade Móvel Socioambiental (UMS)','dd/mm/aaaa - UMS - Local'],['9','Atividades Complementares (DDS, treinamentos e campanhas internas)','dd/mm/aaaa - DDS - Tema - Local'],['3','Atividades desenvolvidas no período (tabela e fotos por frente)','dd/mm/aaaa - Endereço - Atividade']].map(([item,titulo,legenda])=>({item,titulo,legenda}))};}
if(nome==='salvarEntregaRelatoCPT'){entregaDemo={...p,versao:p.versao+1,alteradoPor:perfilDemo.email,alteradoEm:new Date().toISOString()};window.CPT_SITUACAO={...(window.CPT_SITUACAO||{}),[p.id]:p.situacao};return {entrega:entregaDemo,resultado:'Revisão demonstrativa salva apenas nesta prévia.'};}
if(nome==='listarEquipeCPT')return {pessoas:equipeDemo,agendaUrl:'https://docs.google.com/spreadsheets/'};
if(nome==='salvarPessoaCPT'){const i=equipeDemo.findIndex(x=>x.email===p.email);if(i>=0)equipeDemo[i]=p;else equipeDemo.push(p);return {resultado:'Cadastro demonstrativo atualizado.'};}
if(nome==='conferirSaudeCPT')return {itens:[{nome:'Registros',quantidade:54,unidade:'registros',orientacao:'Dados fictícios desta prévia.'}],tempoServidorMs:120};
throw new Error('Operação indisponível na prévia.');}};
</script>'''
s=(root/'src/Aplicacao.html').read_text().replace("<?!= incluirCPT_('Estilos'); ?>",'<meta name="viewport" content="width=device-width, initial-scale=1"><title>CPT · Prévia demonstrativa</title>'+ (root/'src/Estilos.html').read_text()).replace("<?!= incluirCPT_('Interacoes'); ?>",mock+(root/'src/Interacoes.html').read_text())
s=s.replace("<?!= incluirCPT_('Agenda'); ?>",(root/'src/Agenda.html').read_text())
s=s.replace("<?!= incluirCPT_('Entregas'); ?>",(root/'src/Entregas.html').read_text())
# ?inicial=1 simula o perfil já embutido pelo doGet (como na implantação real).
s=s.replace("<script>window.CPT_INICIAL=<?!= inicial ?>;</script>","<script>if(new URLSearchParams(location.search).get('inicial'))window.CPT_INICIAL={perfil:{email:'victor@example.com',nome:'Victor Xavier',ativo:true,papeis:['administrador','administrativo','gestao','atendimento','socioambiental','comunicacao','comercializacao']},conta:'victor@example.com',mes:'2026-09',versao:'2.2.0'};</script>")
s=s.replace("<?!= incluirCPT_('Inicio'); ?>",(root/'src/Inicio.html').read_text())
s=s.replace("<?!= incluirCPT_('Atendimentos'); ?>",(root/'src/Atendimentos.html').read_text())
s=s.replace("<?!= incluirCPT_('Obras'); ?>",(root/'src/Obras.html').read_text())
s=s.replace("<?!= incluirCPT_('Fechamento'); ?>",(root/'src/Fechamento.html').read_text())
s=s.replace("<?!= incluirCPT_('Socioambiental'); ?>",(root/'src/Socioambiental.html').read_text())
(root/'previa/CPT_Previa_1_2_1.html').write_text(s)
