from pathlib import Path
root=Path(__file__).resolve().parents[1]
mock=r'''<script>
const perfilDemo={email:'victor@example.com',nome:'Victor Xavier',ativo:true,papeis:['administrador','administrativo','gestao','atendimento','socioambiental','comunicacao','comercializacao']};
let obsDemo=[];
const equipeDemo=[perfilDemo,{email:'paula@example.com',nome:'Comunicadora de exemplo',ativo:true,papeis:['comunicacao']},{email:'social@example.com',nome:'Equipe social de exemplo',ativo:true,papeis:['socioambiental']}];
let entregaDemo=null;
let eventosDemo=[{id:'AG-demo1',versao:1,titulo:'Sensibilização com moradores',data:'2026-09-30',inicio:'09:00',fim:'10:30',frentes:['socioambiental','comunicacao'],responsaveis:['social@example.com','paula@example.com'],natureza:'externo',status:'confirmada',descricao:'Atividade fictícia para explorar a interface.',obra:'Frente demonstrativa',bairro:'Vila Linda',alteradoPor:'victor@example.com',podeEditar:true},{id:'AG-demo2',versao:1,titulo:'Conferência das entregas do mês',data:'2026-09-30',inicio:'14:00',fim:'15:00',frentes:['administrativo'],responsaveis:['victor@example.com'],natureza:'interno',status:'planejada',descricao:'Exemplo de planejamento interno.',obra:'',bairro:'',alteradoPor:'victor@example.com',podeEditar:true}];
window.CPT_PREVIA={chamar:async function(nome,p){await new Promise(r=>setTimeout(r,180));
const registros=Array.from({length:36},(_,i)=>({id:'REG-'+String(i).padStart(24,'0'),procedimento:i%3?'Relato de atividade':'Pesquisa de Satisfação',data:'2026-09-'+String(28-i%22).padStart(2,'0'),atividade:['Diálogo com moradores','Sensibilização em frente de obra','Água, cuidado e território'][i%3],bairro:['Vila Linda','Jardim do Estádio','Vila Assunção'][i%3],responsavel:'Equipe de exemplo',obra:'Frente de obra demonstrativa',origem:'Dados fictícios',conferencia:''}));
const casos=Array.from({length:7},(_,i)=>({protocolo:'DEMO-'+(100+i),nome:'Pessoa de exemplo '+(i+1),assunto:['Orientação sobre a obra','Solicitação de vistoria','Recomposição da calçada'][i%3],endereco:'Endereço fictício · Santo André',area:'Atendimento',status:i<2?'Concluído':'Em acompanhamento',concluido:i<2,abertura:'2026-09-12',conclusao:i<2?'2026-09-28':'',responsavel:'Equipe de exemplo',obra:'Frente demonstrativa',origem:'Demonstração',proximaAcao:'Conferir o retorno da equipe responsável.',atualizacao:'Informação fictícia para demonstrar a interface.'}));
if(nome==='carregarPerfilCPT'){const forced=new URLSearchParams(location.search).get('perfil');if(forced==='negado')throw new Error('Sua conta (alguem@veolia.com) ainda não está cadastrada ou está inativa. Peça à administração técnica para liberar seu acesso em Equipe e acessos.');return {conta:perfilDemo.email,perfil:forced?{...perfilDemo,nome:'Paula',papeis:[forced]}:perfilDemo,versao:'2.0.0'};}
if(nome==='listarObservacoesCPT')return {protocolo:p.protocolo,itens:obsDemo.filter(x=>x.protocolo===p.protocolo).slice().reverse()};
if(nome==='adicionarObservacaoCPT'){const o={id:'OBS-'+crypto.randomUUID(),protocolo:p.protocolo,consultado:p.protocolo,em:new Date().toISOString(),autor:perfilDemo.email,nome:perfilDemo.nome,canal:p.canal,texto:p.texto};obsDemo.push(o);return {resultado:'Observação registrada no caso '+p.protocolo+'.',observacao:o};}
if(nome==='conferirMeuAcessoCPT')return {etapas:[{nome:'Conta Google',ok:true,mensagem:'alguem@veolia.com'},{nome:'Cadastro na aplicação',ok:false,mensagem:'Conta não cadastrada.'}]};
if(nome==='carregarInicioCPT')return {perfil:perfilDemo,comparacao:{anterior:42},conta:'Prévia demonstrativa',atualizadoEm:new Date().toISOString(),mes:p,indicadores:{registros:54,participacoes:249,abertos:5,concluidos:2,relatosSemPublico:3},procedimentos:[{nome:'Relato de atividade',quantidade:31},{nome:'Pesquisa de Satisfação',quantidade:12},{nome:'Acompanhamento de Vistoria Cautelar',quantidade:7},{nome:'Diagnóstico de Área',quantidade:4}],dias:[2,3,4,7,8,9,10,11,14,15,16,17,18,21,22,23,24,25,28].map((v,i)=>({data:'2026-09-'+String(v).padStart(2,'0'),quantidade:i===0?1:[2,4,3,1,5][i%5]})),recentes:registros.slice(0,5),filtros:{obras:['Frente de obra demonstrativa'],procedimentos:['Relato de atividade','Pesquisa de Satisfação'],bairros:['Vila Linda','Jardim do Estádio','Vila Assunção']},links:{}};
if(nome==='buscarRegistrosCPT'){const rows=registros.filter(r=>(!p.busca||JSON.stringify(r).toLowerCase().includes(p.busca.toLowerCase()))&&(!p.procedimento||r.procedimento===p.procedimento)&&(!p.bairro||r.bairro===p.bairro)&&p.mes==='2026-09');const start=Number(p.cursor||0);return {itens:rows.slice(start,start+24),proximoCursor:start+24<rows.length?String(start+24):null};}
if(nome==='abrirRegistroCPT')return {registro:registros.find(r=>r.id===p),anexos:[],campos:[{titulo:'Como foi a atividade?',valor:'A equipe conversou com os moradores sobre o andamento da obra e registrou as dúvidas para acompanhamento. Este texto é apenas demonstrativo.'},{titulo:'Participantes informados',valor:18}]};
if(nome==='buscarAtendimentosCPT'){const rows=casos.filter(r=>(!p.estado||(p.estado==='concluidos')===r.concluido)&&(!p.busca||JSON.stringify(r).toLowerCase().includes(p.busca.toLowerCase())));return {itens:rows,total:rows.length,proximaPagina:null};}
if(nome==='abrirAtendimentoCPT')return {ficha:casos.find(r=>r.protocolo===p),protocoloConsultado:p};
if(nome==='carregarCronogramaCPT')return {itens:eventosDemo.filter(e=>e.data.startsWith(p.mes)),pessoas:equipeDemo,perfil:perfilDemo};
if(nome==='salvarAtividadeCPT'){const e={...p,id:p.id||'AG-'+crypto.randomUUID(),versao:Number(p.versao||0)+1,podeEditar:true,alteradoPor:perfilDemo.email};eventosDemo=eventosDemo.filter(x=>x.id!==e.id).concat([e]);return {resultado:'Salvo apenas nesta prévia. Nenhuma planilha foi alterada.',evento:e};}
if(nome==='historicoAtividadeCPT')return {versoes:eventosDemo.filter(e=>e.id===p)};
if(nome==='consultarHistoricoFichaCPT')return {itens:[{id:'MOV-demo',protocolo:p.protocolo,data:'30/09/2026 09:00',tipo:'Atualização demonstrativa',status:'Em acompanhamento',autor:'Equipe de exemplo',resumo:'Contato com o morador registrado. Dado fictício.'}],proximoCursor:null};
if(nome==='carregarEntregaRelatoCPT'){const fonte=await window.CPT_PREVIA.chamar('abrirRegistroCPT',p);return {fonte,hash:'demo-hash',entrega:entregaDemo,historico:[]};}
if(nome==='salvarEntregaRelatoCPT'){entregaDemo={...p,versao:p.versao+1,alteradoPor:perfilDemo.email,alteradoEm:new Date().toISOString()};return {entrega:entregaDemo,resultado:'Revisão demonstrativa salva apenas nesta prévia.'};}
if(nome==='listarEquipeCPT')return {pessoas:equipeDemo,agendaUrl:'https://docs.google.com/spreadsheets/'};
if(nome==='salvarPessoaCPT'){const i=equipeDemo.findIndex(x=>x.email===p.email);if(i>=0)equipeDemo[i]=p;else equipeDemo.push(p);return {resultado:'Cadastro demonstrativo atualizado.'};}
if(nome==='conferirSaudeCPT')return {itens:[{nome:'Registros',quantidade:54,unidade:'registros',orientacao:'Dados fictícios desta prévia.'}],tempoServidorMs:120};
throw new Error('Operação indisponível na prévia.');}};
</script>'''
s=(root/'src/Aplicacao.html').read_text().replace("<?!= incluirCPT_('Estilos'); ?>",'<meta name="viewport" content="width=device-width, initial-scale=1"><title>CPT · Prévia demonstrativa</title>'+ (root/'src/Estilos.html').read_text()).replace("<?!= incluirCPT_('Interacoes'); ?>",mock+(root/'src/Interacoes.html').read_text())
s=s.replace("<?!= incluirCPT_('Agenda'); ?>",(root/'src/Agenda.html').read_text())
s=s.replace("<?!= incluirCPT_('Entregas'); ?>",(root/'src/Entregas.html').read_text())
(root/'previa/CPT_Previa_1_2_1.html').write_text(s)
